SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/OrbSimGeneralToolbox.cpp File Reference
OrbSimGeneralToolbox.cpp File Reference
#include <iostream>
#include <iomanip>
#include <limits>
#include <stdio.h>
#include <stdlib.h>
#include <vector>
#include <math.h>
#include <sstream>
#include <string>
#include <fstream>
#include <functional>
#include <algorithm>
#include <numeric>
#include "orbToolboxes.h"
Functions
outputDataType odtStart (outputDataType ODT, int numTotalSamples)
outputDataType odtFinish (outputDataType ODT)
eccArgPeri2ToTcType eccArgPeri2ToTcCalc (eccArgPeri2ToTcType EATT)
double atanTopBtm (double top, double btm)
eccArgPeriCalcType eccArgPeriCalc (eccArgPeriCalcType EACT)
TAcalcReturnType TAcalculator (TAcalcInputType TACIT)
double chiSquaredCalc (double real, double inv_var, double model)
void fileWriter (outputDataType ODT)
void logFileWriter (string filename, string LOGlines)
DItools DItoolsParamLoadUp (DIdataObj DIdo)
VRcalcStarStar VRcalcStarStarLoadUp (RVdataObj RVdo)
VRcalcStarPlanet VRcalcStarPlanetLoadUp (RVdataObj RVdo)
semiMajorType semiMajorConverter (semiMajorType SMT)
double earliestEpochFinder (DIdataObj DIdo, RVdataObj RVdo)
string CorrelationLengthCalc (vector< double > data, string paramName, vector< int > timesBeenHere)
double standardDeviation (vector< double > v)
double meanCalc (vector< double > v, int lastPoint)
void gelmanRubinStage1 (outputDataType ODT, int numTimes)
vector< double > fillOutDataVector (vector< double > data, vector< int > timesBeenHere)
GRfuncReturnType gelmanRubinStage1func (vector< double > data, vector< int > timesBeenHere, int numTimes)
int corrLengthJumpyCalc (vector< double > data)
double varianceCalc (vector< double > data, int lastPoint)
string numSamplesStringMaker (int numSamples)
string findDirectory (string str)
string fileBasename (string str)
string findChainNumberStr (string str)
string filenameEndAppend (string inputString, string endAppendString)
string filenamePrepend (string inputString, string prependString)
string boolToStr (bool boolIN)
string timeStr (int timeElapsed)
Detailed Description
Definition in file OrbSimGeneralToolbox.cpp.
Function Documentation
double atanTopBtm (double top, double btm)
Definition at line 220 of file OrbSimGeneralToolbox.cpp.
References PI.
Referenced by eccArgPeriCalc().
string boolToStr (bool boolIN)
Convert a boolean into a "true"/"false" string.
Definition at line 1499 of file OrbSimGeneralToolbox.cpp.
Referenced by simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
double chiSquaredCalc (double real, double inv_var, double model)
Calculate the Chi Squared value. Note: inv_var is the inverse variance.
Definition at line 458 of file OrbSimGeneralToolbox.cpp.
Referenced by main(), DItools::multiEpochOrbCalc(), toolboxes.DItoolbox::multiEpochOrbCalc(), toolboxes.DItoolbox::multiEpochOrbCalc3(), toolboxes.DItoolbox::multiEpochOrbCalcTH_I(), toolboxes.DItoolbox::multiEpochOrbCalcTH_I3(), toolboxes.RVtoolbox::rv1bodyCalculator(), toolboxes.RVtoolbox::rv1bodyCalculator2(), toolboxes.RVtoolbox::rv2bodyCalculator3(), toolboxes.RVtoolbox::rv2bodyCalculator4(), toolboxes.plotToolbox::rvFitPlotter1Body(), toolboxes.plotToolbox::rvModDatasetMakerDuo(), toolboxes.plotToolbox::rvPlotterDuo(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
string CorrelationLengthCalc (vector< double > data, string paramName, vector< int > timesBeenHere)
Given a single column of data from an MCMC chain, and the associated timesBeenHere column, this function will calculate its Correlation Length. To speed up this process, a 'jumpy' calculator has been written that takes jumps ahead in the chain until it has passed the correlation length and will go back to the previous jump and calculate it for each individual step till it finds the exact step that the correlation length reached the (Variance at this step) = (variance of entire chain)/2.0.
Definition at line 799 of file OrbSimGeneralToolbox.cpp.
References corrLengthJumpyCalc(), and fillOutDataVector().
Referenced by main().
int corrLengthJumpyCalc (vector< double > data)
a 'jumpy' calculator has been written that takes jumps ahead in the chain until it has passed the correlation length and will go back to the previous jump and calculate it for each individual step till it finds the exact step that the correlation length reached the (Variance at this step) = (variance of entire chain)/2.0.
Definition at line 1276 of file OrbSimGeneralToolbox.cpp.
References varianceCalc().
Referenced by CorrelationLengthCalc().
DItools DItoolsParamLoadUp (DIdataObj DIdo)
A function to load up a DItools object with the values in a DIdataObj.
Definition at line 577 of file OrbSimGeneralToolbox.cpp.
References DItools::epochs_DI, DIdataObj::epochs_DI, DataObj::Mass1, DItools::Mass1, DItools::Mass2, DItools::PA_errors, DIdataObj::PA_errors, DItools::PAs_deg_observed, DIdataObj::PAs_deg_observed, DataObj::planet_MsinI, DItools::SA_errors, DIdataObj::SA_errors, DItools::SAs_arcsec_observed, DIdataObj::SAs_arcsec_observed, DataObj::star_Mass2, DataObj::Sys_Dist_PC, DItools::Sys_Dist_PC, and BinaryOrbSimStarterDuo::verboseInternal.
Referenced by main().
double earliestEpochFinder (DIdataObj DIdo, RVdataObj RVdo)
In order to ensure that the date ranges being used for the Time of Last Periapsis has an appropriate latest value, it the earliest value between the RV and DI data must be found, as done by this function. The JD value of the earliest epoch is returned as a double.
Definition at line 755 of file OrbSimGeneralToolbox.cpp.
References DIdataObj::epochs_DI, RVdataObj::epochs_RV, and BinaryOrbSimStarterDuo::verbose.
Referenced by main().
eccArgPeri2ToTcType eccArgPeri2ToTcCalc (eccArgPeri2ToTcType EATT)
Convert the provided Eccentricity and Argument of Periapsis into Time of Center transit and Time of Last Periapsis.
Definition at line 71 of file OrbSimGeneralToolbox.cpp.
References eccArgPeri2ToTcType::argPeri_deg, eccArgPeri2ToTcType::e, eccArgPeri2ToTcType::period, PI, eccArgPeri2ToTcType::Tc, eccArgPeri2ToTcType::To, and BinaryOrbSimStarterDuo::verbose.
Referenced by toolboxes.plotToolbox::rvPlotterDuo(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
eccArgPeriCalcType eccArgPeriCalc (eccArgPeriCalcType EACT)
Calculate the Eccentricity and Argument of Periapsis from the provided sqrt(e*sin(ArgPeri)) and sqrt(e*cos(ArgPeri)) values.
Definition at line 249 of file OrbSimGeneralToolbox.cpp.
References eccArgPeriCalcType::argPeri_deg, atanTopBtm(), eccArgPeriCalcType::e, PI, eccArgPeriCalcType::sqrtEcosArgPeri, eccArgPeriCalcType::sqrtEsinArgPeri, and BinaryOrbSimStarterDuo::verbose.
string fileBasename (string str)
Given a string of the full path to a file, this will find and return the basename of the file without the path.
Definition at line 1399 of file OrbSimGeneralToolbox.cpp.
string filenameEndAppend (string inputString, string endAppendString)
A function to append a string onto the end of a file name taking the extension and path properly into account.
NOTE: ******** THIS COULD PROBABLY BE RE-WRITTEN TO USE STR.FIND() AND STR.SUBSTR() ***
Definition at line 1426 of file OrbSimGeneralToolbox.cpp.
References BinaryOrbSimStarterDuo::verboseInternal.
string filenamePrepend (string inputString, string prependString)
A function to append a string onto the beginning of a file name taking the path properly into account.
NOTE: ******** THIS COULD PROBABLY BE RE-WRITTEN TO USE STR.FIND() AND STR.SUBSTR() ***
Definition at line 1460 of file OrbSimGeneralToolbox.cpp.
References BinaryOrbSimStarterDuo::verboseInternal.
Referenced by main().
void fileWriter (outputDataType ODT)
Write an outputDataType to an output txt or dat file (default is dat). This file will have the variables in the object written with one value per column and one step in the chain per line. The precision of each variable has been turned to minimize file size while retaining the ability to ensure calculations from these values will be sufficiently accurate. The spacing between each column has also been perfected to produce nice looking output files.
Format will be: longAN [deg] e [N/A] To [julian date] Tc [julian date] period [yrs] inclination [deg] argPeri [deg] a_total [AU] chiSquared K [m/s] RVorigin_* [m/s] timesBeenHere
Note: There will be one column for each RVorigin.
Definition at line 479 of file OrbSimGeneralToolbox.cpp.
References outputDataType::a_totals, outputDataType::argPeri_degs, outputDataType::chiSquareds, outputDataType::data_filename, outputDataType::es, outputDataType::inclination_degs, outputDataType::Ks, outputDataType::longAN_degs, outputDataType::numSamplesAccepted, outputDataType::periods, outputDataType::RVoffsets, outputDataType::Tcs, outputDataType::timesBeenHeres, and outputDataType::Ts.
Referenced by main().
vector<double> fillOutDataVector (vector< double > data, vector< int > timesBeenHere)
Puts data into proper vector taking timesBeenHere into account.
Note: Caution, the timesBeenHere feature compacts the vector size to be approximately 30% of its total size and this function expands it to its full size.
Definition at line 1177 of file OrbSimGeneralToolbox.cpp.
Referenced by CorrelationLengthCalc(), and gelmanRubinStage1func().
string findChainNumberStr (string str)
Python provides the a log file name to CPP when it makes the call to start a MCMC or SimAnneal run. This function will find the chain number from that string and return it.
Definition at line 1412 of file OrbSimGeneralToolbox.cpp.
Referenced by gelmanRubinStage1().
string findDirectory (string str)
Given a string of the full path to a file, this will find and return the directory the file is in.
Definition at line 1387 of file OrbSimGeneralToolbox.cpp.
Referenced by gelmanRubinStage1().
void gelmanRubinStage1 (outputDataType ODT, int numTimes)
This function will calculate the variance and mean numTimes times for each parameter and then write output to a file to be read in by Python function 'gelmanRubinStage2' to finish the calculations and write the final file to disk. It utilizes the gelmanRubinStage1Func to perform the actual calculations requested to assist in keeping the code in this function cleaner. In an attempt to save RAM while making these heavy calculations, the 'empty' columns of data in the outputDataType are found and cleared and swapped with empty vectors, but it is not sure yet if the method implemented to do this works completely. As such, this function could see some future upgrades if a better method is found.
Note: Feel free to contact the author (kylem.nosp@m.ede@.nosp@m.astro.nosp@m.n.s..nosp@m.u-tok.nosp@m.yo.a.nosp@m.c.jp) with any suggestions for fixing the memory saving sections in this function.
Definition at line 883 of file OrbSimGeneralToolbox.cpp.
References outputDataType::a_totals, outputDataType::argPeri_degs, outputDataType::chiSquareds, outputDataType::data_filename, outputDataType::es, findChainNumberStr(), findDirectory(), gelmanRubinStage1func(), outputDataType::inclination_degs, outputDataType::Ks, GRfuncReturnType::Lcs, outputDataType::longAN_degs, GRfuncReturnType::means, outputDataType::periods, outputDataType::RVoffsets, outputDataType::Tcs, outputDataType::timesBeenHeres, outputDataType::Ts, GRfuncReturnType::vars, and BinaryOrbSimStarterDuo::verbose.
Referenced by main().
GRfuncReturnType gelmanRubinStage1func (vector< double > data, vector< int > timesBeenHere, int numTimes)
This function will calculate the variance and mean numTimes times for a single parameter and pass it back to gelmanRubinStage1 which called it.
Definition at line 1205 of file OrbSimGeneralToolbox.cpp.
References fillOutDataVector(), GRfuncReturnType::Lcs, meanCalc(), GRfuncReturnType::means, varianceCalc(), GRfuncReturnType::vars, and BinaryOrbSimStarterDuo::verbose.
Referenced by gelmanRubinStage1().
void logFileWriter (string filename, string LOGlines)
Throughout the CPP code, the log lines are stored into a stringstream which is then passed into this function to be written to an output file.
Definition at line 531 of file OrbSimGeneralToolbox.cpp.
Referenced by main().
double meanCalc (vector< double > v, int lastPoint)
A very simple function that simply adds up the total of all the elements in a vector<double> and divides it by the number of elements to give the mean value. The precision of the calculation is checked to make sure the result is sufficiently precise.
Definition at line 855 of file OrbSimGeneralToolbox.cpp.
References BinaryOrbSimStarterDuo::verbose.
Referenced by gelmanRubinStage1func(), and varianceCalc().
string numSamplesStringMaker (int numSamples)
A function to take the number of samples as an integer and convert it to a nicely formated string. EX. 1,000,000 -> "1-Million".
Definition at line 1341 of file OrbSimGeneralToolbox.cpp.
References BinaryOrbSimStarterDuo::numSamples, and BinaryOrbSimStarterDuo::numSamplesString.
Referenced by main().
outputDataType odtFinish (outputDataType ODT)
An attempt to clear out the extra memory of the space allocated to the variables in an outputDataType object after a chain is complete. Unfortunately, this function does not seem to be releasing the memory back to the OS at the moment... Hopefully it can be fixed or a better method will be implemented in the future to handle this issue.
Definition at line 47 of file OrbSimGeneralToolbox.cpp.
Referenced by MCMCorbFuncObj::simulator().
outputDataType odtStart (outputDataType ODT, int numTotalSamples)
Definition at line 18 of file OrbSimGeneralToolbox.cpp.
References outputDataType::a_totals, outputDataType::argPeri_degs, outputDataType::chiSquareds, outputDataType::es, outputDataType::inclination_degs, outputDataType::Ks, outputDataType::longAN_degs, outputDataType::periods, outputDataType::Tcs, outputDataType::timesBeenHeres, and outputDataType::Ts.
Referenced by MCMCorbFuncObj::simulator().
semiMajorType semiMajorConverter (semiMajorType SMT)
A function to determine the missing values of the possible semi-major axes (a1,a2,a_total) given any one of them and the individual masses of the two objects.
Definition at line 680 of file OrbSimGeneralToolbox.cpp.
References semiMajorType::a1, semiMajorType::a2, semiMajorType::a_total, GravConst, KGperMsun, semiMajorType::Mass1, semiMajorType::Mass2, MperAU, semiMajorType::period, PI, SecPerYear, and BinaryOrbSimStarterDuo::verboseInternal.
Referenced by toolboxes.plotToolbox::rvFitPlotter1Body(), toolboxes.plotToolbox::rvModDatasetMakerDuo(), toolboxes.plotToolbox::rvPlotterDuo(), VRcalcStarPlanetLoadUp(), and VRcalcStarStarLoadUp().
double standardDeviation (vector< double > v)
Calculates the standard deviation utilizing the varianceCalc based on the code in Numerical Recipes 3rd and simply taking the square root of its output and returning it as a double.
Definition at line 830 of file OrbSimGeneralToolbox.cpp.
References varianceCalc().
TAcalcReturnType TAcalculator (TAcalcInputType TACIT)
Calculate the True Anomaly for a particular epoch of data.
Definition at line 318 of file OrbSimGeneralToolbox.cpp.
References TAcalcInputType::e, TAcalcReturnType::E_deg, n, TAcalcInputType::period, PI, TAcalcInputType::t, TAcalcInputType::T, TAcalcReturnType::TA_deg, TAcalcInputType::Tc, and TAcalcInputType::verbose.
Referenced by VRcalcStarStar::multiEpochCalc(), VRcalcStarPlanet::multiEpochCalc(), DItools::multiEpochOrbCalc(), toolboxes.DItoolbox::multiEpochOrbCalcTH_I(), and toolboxes.DItoolbox::multiEpochOrbCalcTH_I3().
string timeStr (int timeElapsed)
Convert the timeElapsed integer, which is in seconds, into a nicely formated string. EX. "* hour(s) and * minute(s)"
Definition at line 1514 of file OrbSimGeneralToolbox.cpp.
References toolboxes.generalToolbox::timeString(), and BinaryOrbSimStarterDuo::verbose.
Referenced by main().
double varianceCalc (vector< double > data, int lastPoint)
This will calculate the "bias-corrected sample variance" and uses an advanced "corrected two-pass algorithm" to reduce roundoff error, a modified version of function on pg 728 of Numerical Recipes 3rd.
Definition at line 1316 of file OrbSimGeneralToolbox.cpp.
References meanCalc(), and n.
Referenced by corrLengthJumpyCalc(), gelmanRubinStage1func(), and standardDeviation().
VRcalcStarPlanet VRcalcStarPlanetLoadUp (RVdataObj RVdo)
A function to load up a VRcalcStarPlanet object with the values in the general RVdataObj.
Definition at line 636 of file OrbSimGeneralToolbox.cpp.
References semiMajorType::a1, VRcalcStarPlanet::a1, semiMajorType::a2, semiMajorType::a_total, VRcalcStarPlanet::a_total, VRcalcStarPlanet::argPeri_deg_p, VRcalcStarPlanet::e_p, VRcalcStarPlanet::inclination_deg_p, VRcalcStarPlanet::K_p, VRcalcStarPlanet::K_p_error, RVtools::Mass1, DataObj::Mass1, semiMajorType::Mass1, semiMajorType::Mass2, VRcalcStarPlanet::Mass2sinI_p, semiMajorType::period, VRcalcStarPlanet::period_p, DataObj::planet_argPeri, DataObj::planet_e, DataObj::planet_inc, DataObj::planet_K, DataObj::planet_K_error, DataObj::planet_MsinI, DataObj::planet_P, DataObj::planet_T, DataObj::planet_Tc, semiMajorConverter(), VRcalcStarPlanet::T_p, and VRcalcStarPlanet::Tc_p.
Referenced by main(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
VRcalcStarStar VRcalcStarStarLoadUp (RVdataObj RVdo)
A function to load up a VRcalcStarStar object with the values in the general RVdataObj.
Definition at line 603 of file OrbSimGeneralToolbox.cpp.
References VRcalcStarStar::a1, semiMajorType::a1, semiMajorType::a2, VRcalcStarStar::a_total, semiMajorType::a_total, VRcalcStarStar::argPeri_deg_s, VRcalcStarStar::e_s, VRcalcStarStar::inclination_deg_s, RVtools::Mass1, DataObj::Mass1, semiMajorType::Mass1, semiMajorType::Mass2, VRcalcStarStar::Mass2_s, semiMajorType::period, VRcalcStarStar::period_s, semiMajorConverter(), DataObj::star_argPeri, DataObj::star_e, DataObj::star_inc, DataObj::star_Mass2, DataObj::star_P, DataObj::star_T, DataObj::star_Tc, VRcalcStarStar::T_s, and VRcalcStarStar::Tc_s.
Referenced by main(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().