SMODT-documentation: TRandomCombined< RG1, RG2 > Class Template Reference
TRandomCombined< RG1, RG2 > Class Template Reference
Public Member Functions
TRandomCombined (int seed)
void RandomInit (int seed)
double Random ()
int IRandom (int min, int max)
TRandomCombined (int seed)
void RandomInit (int seed)
double Random ()
int IRandom (int min, int max)
Detailed Description
template<class RG1, class RG2>
class TRandomCombined< RG1, RG2 >
Definition at line 32 of file rancombi.cpp.
Constructor & Destructor Documentation
template<class RG1, class RG2> TRandomCombined< RG1, RG2 >::TRandomCombined (int seed) inline
Definition at line 34 of file rancombi.cpp.
template<class RG1, class RG2> TRandomCombined< RG1, RG2 >::TRandomCombined (int seed) inline
Definition at line 34 of file rancombi.cpp.
Member Function Documentation
template<class RG1, class RG2> int TRandomCombined< RG1, RG2 >::IRandom (int min, int max) inline
Definition at line 47 of file rancombi.cpp.
References TRandomCombined< RG1, RG2 >::Random().
Referenced by main().
template<class RG1, class RG2> int TRandomCombined< RG1, RG2 >::IRandom (int min, int max) inline
Definition at line 47 of file rancombi.cpp.
References TRandomCombined< RG1, RG2 >::Random().
template<class RG1, class RG2> double TRandomCombined< RG1, RG2 >::Random () inline
Definition at line 41 of file rancombi.cpp.
References TRandomCombined< RG1, RG2 >::Random().
template<class RG1, class RG2> double TRandomCombined< RG1, RG2 >::Random () inline
Definition at line 41 of file rancombi.cpp.
Referenced by TRandomCombined< RG1, RG2 >::IRandom(), main(), and TRandomCombined< RG1, RG2 >::Random().
template<class RG1, class RG2> void TRandomCombined< RG1, RG2 >::RandomInit (int seed) inline
Definition at line 36 of file rancombi.cpp.
References TRandomCombined< RG1, RG2 >::RandomInit().
template<class RG1, class RG2> void TRandomCombined< RG1, RG2 >::RandomInit (int seed) inline
Definition at line 36 of file rancombi.cpp.
Referenced by TRandomCombined< RG1, RG2 >::RandomInit().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/rancombi.cpp
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/rancombi.cpp