SMODT-documentation: CRandomSFMT Class Reference
CRandomSFMT Class Reference
#include <sfmt.h>
Public Member Functions
CRandomSFMT (int seed, int IncludeMother=1)
void RandomInit (int seed)
void RandomInitByArray (int const seeds[], int NumSeeds)
int IRandom (int min, int max)
int IRandomX (int min, int max)
double Random ()
double UniformRandom (double min, double max)
uint32_t BRandom ()
CRandomSFMT (int seed, int IncludeMother=1)
void RandomInit (int seed)
void RandomInitByArray (int const seeds[], int NumSeeds)
int IRandom (int min, int max)
int IRandomX (int min, int max)
double Random ()
double UniformRandom (double min, double max)
uint32_t BRandom ()
Private Member Functions
void Init2 ()
void Generate ()
uint32_t MotherBits ()
void Init2 ()
void Generate ()
uint32_t MotherBits ()
Private Attributes
uint32_t ix
uint32_t LastInterval
uint32_t RLimit
uint32_t UseMother
__m128i mask
__m128i state [SFMT_N]
uint32_t MotherState [5]
Detailed Description
Definition at line 213 of file sfmt.h.
Constructor & Destructor Documentation
CRandomSFMT::CRandomSFMT (int seed, int IncludeMother = 1) inline
Definition at line 215 of file sfmt.h.
References LastInterval, RandomInit(), and UseMother.
CRandomSFMT::CRandomSFMT (int seed, int IncludeMother = 1) inline
Definition at line 215 of file sfmt.h.
References LastInterval, RandomInit(), and UseMother.
Member Function Documentation
uint32_t CRandomSFMT::BRandom ()
Definition at line 265 of file sfmt.cpp.
References Generate(), ix, MotherBits(), SFMT_N, state, and UseMother.
Referenced by IRandom(), and IRandomX().
uint32_t CRandomSFMT::BRandom ()
void CRandomSFMT::Generate () private
Definition at line 243 of file sfmt.cpp.
References ix, mask, SFMT_M, SFMT_N, sfmt_recursion(), and state.
Referenced by BRandom(), Init2(), Random(), and UniformRandom().
void CRandomSFMT::Generate () private
void CRandomSFMT::Init2 () private
Definition at line 188 of file sfmt.cpp.
References Generate(), mask, SFMT_MASK, SFMT_PARITY, and state.
Referenced by RandomInit(), and RandomInitByArray().
void CRandomSFMT::Init2 () private
int CRandomSFMT::IRandom (int min, int max)
Definition at line 294 of file sfmt.cpp.
References BRandom().
int CRandomSFMT::IRandom (int min, int max)
int CRandomSFMT::IRandomX (int min, int max)
Definition at line 312 of file sfmt.cpp.
References BRandom(), LastInterval, and RLimit.
Referenced by simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
int CRandomSFMT::IRandomX (int min, int max)
uint32_t CRandomSFMT::MotherBits () private
Definition at line 277 of file sfmt.cpp.
References MotherState.
Referenced by BRandom(), Random(), and UniformRandom().
uint32_t CRandomSFMT::MotherBits () private
double CRandomSFMT::Random ()
Definition at line 348 of file sfmt.cpp.
References Generate(), ix, MotherBits(), MotherState, SFMT_N, state, and UseMother.
double CRandomSFMT::Random ()
void CRandomSFMT::RandomInit (int seed)
void CRandomSFMT::RandomInit (int seed)
Definition at line 78 of file sfmt.cpp.
References Init2(), SFMT_N, state, and UseMother.
Referenced by CRandomSFMT().
void CRandomSFMT::RandomInitByArray (int const seeds[], int NumSeeds)
Definition at line 108 of file sfmt.cpp.
References func1(), func2(), Init2(), MotherState, SFMT_N, state, and UseMother.
void CRandomSFMT::RandomInitByArray (int const seeds[], int NumSeeds)
double CRandomSFMT::UniformRandom (double min, double max)
Definition at line 369 of file sfmt.cpp.
References Generate(), ix, MotherBits(), MotherState, SFMT_N, state, and UseMother.
Referenced by main(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
double CRandomSFMT::UniformRandom (double min, double max)
Member Data Documentation
uint32_t CRandomSFMT::ix private
Definition at line 230 of file sfmt.h.
Referenced by BRandom(), Generate(), Random(), and UniformRandom().
uint32_t CRandomSFMT::LastInterval private
Definition at line 231 of file sfmt.h.
Referenced by CRandomSFMT(), and IRandomX().
__m128i CRandomSFMT::mask private
Definition at line 234 of file sfmt.h.
Referenced by Generate(), and Init2().
uint32_t CRandomSFMT::MotherState private
Definition at line 236 of file sfmt.h.
Referenced by MotherBits(), Random(), RandomInitByArray(), and UniformRandom().
uint32_t CRandomSFMT::RLimit private
Definition at line 232 of file sfmt.h.
Referenced by IRandomX().
__m128i CRandomSFMT::state private
Definition at line 235 of file sfmt.h.
Referenced by BRandom(), Generate(), Init2(), Random(), RandomInit(), RandomInitByArray(), and UniformRandom().
uint32_t CRandomSFMT::UseMother private
Definition at line 233 of file sfmt.h.
Referenced by BRandom(), CRandomSFMT(), Random(), RandomInit(), RandomInitByArray(), and UniformRandom().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/sfmt.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/sfmt.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/sfmt.cpp
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/sfmt.cpp