SMODT-documentation: CWalleniusNCHypergeometric Class Reference
CWalleniusNCHypergeometric Class Reference
#include <stocc.h>
Public Member Functions
CWalleniusNCHypergeometric (int32_t n, int32_t m, int32_t N, double odds, double accuracy=1.E-8)
void SetParameters (int32_t n, int32_t m, int32_t N, double odds)
double probability (int32_t x)
int32_t MakeTable (double *table, int32_t MaxLength, int32_t *xfirst, int32_t *xlast, double cutoff=0.)
double mean (void)
double variance (void)
int32_t mode (void)
double moments (double *mean, double *var)
int BernouilliH (int32_t x, double h, double rh, StochasticLib1 *sto)
CWalleniusNCHypergeometric (int32_t n, int32_t m, int32_t N, double odds, double accuracy=1.E-8)
void SetParameters (int32_t n, int32_t m, int32_t N, double odds)
double probability (int32_t x)
int32_t MakeTable (double *table, int32_t MaxLength, int32_t *xfirst, int32_t *xlast, double cutoff=0.)
double mean (void)
double variance (void)
int32_t mode (void)
double moments (double *mean, double *var)
int BernouilliH (int32_t x, double h, double rh, StochasticLib1 *sto)
Protected Member Functions
double recursive (void)
double binoexpand (void)
double laplace (void)
double integrate (void)
double lnbico (void)
void findpars (void)
double integrate_step (double a, double b)
double search_inflect (double t_from, double t_to)
double recursive (void)
double binoexpand (void)
double laplace (void)
double integrate (void)
double lnbico (void)
void findpars (void)
double integrate_step (double a, double b)
double search_inflect (double t_from, double t_to)
Protected Attributes
double omega
int32_t n
int32_t m
int32_t N
int32_t x
int32_t xmin
int32_t xmax
double accuracy
int32_t xLastBico
double bico
double mFac
double xFac
double r
double rd
double w
double wr
double E
double phi2d
int32_t xLastFindpars
Detailed Description
Definition at line 445 of file stocc.h.
Constructor & Destructor Documentation
CWalleniusNCHypergeometric::CWalleniusNCHypergeometric (int32_t n, int32_t m, int32_t N, double odds, double accuracy = 1.E-8)
Definition at line 324 of file wnchyppr.cpp.
References accuracy, and SetParameters().
CWalleniusNCHypergeometric::CWalleniusNCHypergeometric (int32_t n, int32_t m, int32_t N, double odds, double accuracy = 1.E-8)
Member Function Documentation
int CWalleniusNCHypergeometric::BernouilliH (int32_t x, double h, double rh, StochasticLib1 * sto)
Definition at line 601 of file wnchyppr.cpp.
References bico, E, Erf(), findpars(), LN2, lnbico(), log1mx(), log1pow(), n, StochasticLib1::Normal(), omega, pow2_1(), probability(), r, rd, and w.
Referenced by StochasticLib3::WalleniusNCHypRatioOfUnifoms().
int CWalleniusNCHypergeometric::BernouilliH (int32_t x, double h, double rh, StochasticLib1 * sto)
double CWalleniusNCHypergeometric::binoexpand (void) protected
Definition at line 744 of file wnchyppr.cpp.
References FallingFactorial(), FatalError(), m, n, N, omega, and x.
Referenced by probability().
double CWalleniusNCHypergeometric::binoexpand (void) protected
void CWalleniusNCHypergeometric::findpars (void) protected
Definition at line 525 of file wnchyppr.cpp.
References E, FatalError(), LN2, m, n, N, omega, phi2d, pow2_1(), r, rd, w, wr, x, and xLastFindpars.
Referenced by BernouilliH(), and probability().
void CWalleniusNCHypergeometric::findpars (void) protected
double CWalleniusNCHypergeometric::integrate (void) protected
double CWalleniusNCHypergeometric::integrate (void) protected
Definition at line 919 of file wnchyppr.cpp.
References accuracy, E, integrate_step(), lnbico(), m, n, N, rd, search_inflect(), and w.
Referenced by probability().
double CWalleniusNCHypergeometric::integrate_step (double a, double b) protected
double CWalleniusNCHypergeometric::integrate_step (double a, double b) protected
Definition at line 992 of file wnchyppr.cpp.
References bico, IPOINTS, log1pow(), n, omega, r, and rd.
Referenced by integrate().
double CWalleniusNCHypergeometric::laplace (void) protected
Definition at line 774 of file wnchyppr.cpp.
References accuracy, progressbar.terminal::COLORS, ErfRes, ERFRES_B, ERFRES_L, ERFRES_N, ERFRES_S, FatalError(), FloorLog2(), LN2, lnbico(), log1mx(), n, NumSDev, omega, phi2d, pow2_1(), r, rd, w, and x.
Referenced by probability().
double CWalleniusNCHypergeometric::laplace (void) protected
double CWalleniusNCHypergeometric::lnbico (void) protected
Definition at line 500 of file wnchyppr.cpp.
References bico, FAK_LEN, LnFac(), m, mFac, n, N, x, toolboxes.DItoolbox::x2, xFac, and xLastBico.
Referenced by BernouilliH(), integrate(), laplace(), and probability().
double CWalleniusNCHypergeometric::lnbico (void) protected
int32_t CWalleniusNCHypergeometric::MakeTable (double * table, int32_t MaxLength, int32_t * xfirst, int32_t * xlast, double cutoff = 0.)
int32_t CWalleniusNCHypergeometric::MakeTable (double * table, int32_t MaxLength, int32_t * xfirst, int32_t * xlast, double cutoff = 0.)
Definition at line 1177 of file wnchyppr.cpp.
References accuracy, m, mean(), n, N, NumSD(), omega, probability(), variance(), toolboxes.DItoolbox::x2, xmax, and xmin.
Referenced by StochasticLib3::WalleniusNCHypTable().
double CWalleniusNCHypergeometric::mean (void)
Definition at line 342 of file wnchyppr.cpp.
References E, FatalError(), m, N, n, omega, xmax, and xmin.
Referenced by main(), MakeTable(), mode(), moments(), variance(), StochasticLib3::WalleniusNCHypInversion(), and StochasticLib3::WalleniusNCHypRatioOfUnifoms().
double CWalleniusNCHypergeometric::mean (void)
int32_t CWalleniusNCHypergeometric::mode (void)
int32_t CWalleniusNCHypergeometric::mode (void)
Definition at line 455 of file wnchyppr.cpp.
References m, mean(), N, n, omega, probability(), toolboxes.DItoolbox::x2, xmax, and xmin.
double CWalleniusNCHypergeometric::moments (double * mean, double * var)
double CWalleniusNCHypergeometric::moments (double * mean, double * var)
Definition at line 426 of file wnchyppr.cpp.
References accuracy, E, mean(), probability(), x, xmax, and xmin.
Referenced by main().
double CWalleniusNCHypergeometric::probability (int32_t x)
double CWalleniusNCHypergeometric::probability (int32_t x)
Definition at line 1142 of file wnchyppr.cpp.
References binoexpand(), E, findpars(), integrate(), laplace(), lnbico(), LnFac(), m, n, N, omega, recursive(), w, x, toolboxes.DItoolbox::x2, xmax, and xmin.
Referenced by BernouilliH(), main(), MakeTable(), mode(), moments(), StochasticLib3::MultiWalleniusNCHyp(), CMultiWalleniusNCHypergeometric::probability(), StochasticLib3::WalleniusNCHypInversion(), and StochasticLib3::WalleniusNCHypRatioOfUnifoms().
double CWalleniusNCHypergeometric::recursive (void) protected
Definition at line 692 of file wnchyppr.cpp.
References accuracy, FatalError(), m, N, n, omega, progressbar.example::p, x, and toolboxes.DItoolbox::x2.
Referenced by probability().
double CWalleniusNCHypergeometric::recursive (void) protected
double CWalleniusNCHypergeometric::search_inflect (double t_from, double t_to) protected
Definition at line 1044 of file wnchyppr.cpp.
References progressbar.terminal::COLORS, E, FatalError(), LN2, n, omega, pow2_1(), r, rd, and x.
Referenced by integrate().
double CWalleniusNCHypergeometric::search_inflect (double t_from, double t_to) protected
void CWalleniusNCHypergeometric::SetParameters (int32_t n, int32_t m, int32_t N, double odds)
Definition at line 331 of file wnchyppr.cpp.
References FatalError(), m, n, N, omega, r, xLastBico, xLastFindpars, xmax, and xmin.
Referenced by CWalleniusNCHypergeometric().
void CWalleniusNCHypergeometric::SetParameters (int32_t n, int32_t m, int32_t N, double odds)
double CWalleniusNCHypergeometric::variance (void)
Definition at line 415 of file wnchyppr.cpp.
References m, mean(), n, and N.
Referenced by MakeTable().
double CWalleniusNCHypergeometric::variance (void)
Member Data Documentation
double CWalleniusNCHypergeometric::accuracy protected
Definition at line 476 of file stocc.h.
Referenced by CWalleniusNCHypergeometric(), integrate(), laplace(), MakeTable(), moments(), and recursive().
double CWalleniusNCHypergeometric::bico protected
Definition at line 479 of file stocc.h.
Referenced by BernouilliH(), integrate_step(), and lnbico().
double CWalleniusNCHypergeometric::E protected
Definition at line 481 of file stocc.h.
Referenced by BernouilliH(), findpars(), integrate(), mean(), moments(), probability(), and search_inflect().
int32_t CWalleniusNCHypergeometric::m protected
Definition at line 474 of file stocc.h.
Referenced by binoexpand(), findpars(), integrate(), lnbico(), MakeTable(), mean(), mode(), probability(), recursive(), SetParameters(), and variance().
double CWalleniusNCHypergeometric::mFac protected
Definition at line 479 of file stocc.h.
Referenced by lnbico().
int32_t CWalleniusNCHypergeometric::N protected
Definition at line 474 of file stocc.h.
Referenced by binoexpand(), findpars(), integrate(), lnbico(), MakeTable(), mean(), mode(), probability(), recursive(), SetParameters(), and variance().
int32_t CWalleniusNCHypergeometric::n protected
Definition at line 474 of file stocc.h.
Referenced by BernouilliH(), binoexpand(), findpars(), integrate(), integrate_step(), laplace(), lnbico(), MakeTable(), mean(), mode(), probability(), recursive(), search_inflect(), SetParameters(), and variance().
double CWalleniusNCHypergeometric::omega protected
Definition at line 473 of file stocc.h.
Referenced by BernouilliH(), binoexpand(), findpars(), integrate_step(), laplace(), MakeTable(), mean(), mode(), probability(), recursive(), search_inflect(), and SetParameters().
double CWalleniusNCHypergeometric::phi2d protected
Definition at line 481 of file stocc.h.
Referenced by findpars(), and laplace().
double CWalleniusNCHypergeometric::r protected
Definition at line 481 of file stocc.h.
Referenced by BernouilliH(), findpars(), integrate_step(), laplace(), search_inflect(), and SetParameters().
double CWalleniusNCHypergeometric::rd protected
Definition at line 481 of file stocc.h.
Referenced by BernouilliH(), findpars(), integrate(), integrate_step(), laplace(), and search_inflect().
double CWalleniusNCHypergeometric::w protected
Definition at line 481 of file stocc.h.
Referenced by BernouilliH(), findpars(), integrate(), laplace(), and probability().
double CWalleniusNCHypergeometric::wr protected
Definition at line 481 of file stocc.h.
Referenced by findpars().
int32_t CWalleniusNCHypergeometric::x protected
Definition at line 474 of file stocc.h.
Referenced by binoexpand(), findpars(), laplace(), lnbico(), moments(), probability(), recursive(), and search_inflect().
double CWalleniusNCHypergeometric::xFac protected
Definition at line 479 of file stocc.h.
Referenced by lnbico().
int32_t CWalleniusNCHypergeometric::xLastBico protected
Definition at line 478 of file stocc.h.
Referenced by lnbico(), and SetParameters().
int32_t CWalleniusNCHypergeometric::xLastFindpars protected
Definition at line 482 of file stocc.h.
Referenced by findpars(), and SetParameters().
int32_t CWalleniusNCHypergeometric::xmax protected
Definition at line 475 of file stocc.h.
Referenced by MakeTable(), mean(), mode(), moments(), probability(), and SetParameters().
int32_t CWalleniusNCHypergeometric::xmin protected
Definition at line 475 of file stocc.h.
Referenced by MakeTable(), mean(), mode(), moments(), probability(), and SetParameters().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/stocc.h
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/stocc.h
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/wnchyppr.cpp
/mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/wnchyppr.cpp