SMODT-documentation: StochasticLib1 Class Reference
StochasticLib1 Class Reference
#include <kylesGaussRand.h>
Public Member Functions
StochasticLib1 (int seed)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
StochasticLib1 (int seed)
int Bernoulli (double p)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
int32_t Poisson (double L)
int32_t Binomial (int32_t n, double p)
int32_t Hypergeometric (int32_t n, int32_t m, int32_t N)
void Multinomial (int32_t *destination, double *source, int32_t n, int colors)
void Multinomial (int32_t *destination, int32_t *source, int32_t n, int colors)
void MultiHypergeometric (int32_t *destination, int32_t *source, int32_t n, int colors)
void Shuffle (int *list, int min, int n)
StochasticLib1 (int seed)
int Bernoulli (double p)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
int32_t Poisson (double L)
int32_t Binomial (int32_t n, double p)
int32_t Hypergeometric (int32_t n, int32_t m, int32_t N)
void Multinomial (int32_t *destination, double *source, int32_t n, int colors)
void Multinomial (int32_t *destination, int32_t *source, int32_t n, int colors)
void MultiHypergeometric (int32_t *destination, int32_t *source, int32_t n, int colors)
void Shuffle (int *list, int min, int n)
Protected Member Functions
int32_t PoissonInver (double L)
int32_t PoissonRatioUniforms (double L)
int32_t PoissonLow (double L)
int32_t BinomialInver (int32_t n, double p)
int32_t BinomialRatioOfUniforms (int32_t n, double p)
int32_t HypInversionMod (int32_t n, int32_t M, int32_t N)
int32_t HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N)
int32_t PoissonInver (double L)
int32_t PoissonRatioUniforms (double L)
int32_t PoissonLow (double L)
int32_t BinomialInver (int32_t n, double p)
int32_t BinomialRatioOfUniforms (int32_t n, double p)
int32_t HypInversionMod (int32_t n, int32_t M, int32_t N)
int32_t HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N)
Static Protected Member Functions
static double fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n)
static double fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n)
Protected Attributes
double normal_x2
int normal_x2_valid
int32_t hyp_n_last
int32_t hyp_m_last
int32_t hyp_N_last
int32_t hyp_mode
int32_t hyp_mp
int32_t hyp_bound
double hyp_a
double hyp_h
double hyp_fm
double pois_L_last
double pois_f0
double pois_a
double pois_h
double pois_g
int32_t pois_bound
int32_t bino_n_last
double bino_p_last
int32_t bino_mode
int32_t bino_bound
double bino_a
double bino_h
double bino_g
double bino_r1
Detailed Description
Definition at line 15 of file kylesGaussRand.h.
Constructor & Destructor Documentation
StochasticLib1::StochasticLib1 (int seed)
Definition at line 69 of file kylesGaussRand.cpp.
References normal_x2_valid.
StochasticLib1::StochasticLib1 (int seed)
StochasticLib1::StochasticLib1 (int seed)
Member Function Documentation
int StochasticLib1::Bernoulli (double p)
Definition at line 783 of file stoc1.cpp.
References FatalError(), and progressbar.example::p.
int StochasticLib1::Bernoulli (double p)
int32_t StochasticLib1::Binomial (int32_t n, double p)
Reimplemented in StochasticLib2, and StochasticLib2.
Definition at line 508 of file stoc1.cpp.
References BinomialInver(), BinomialRatioOfUniforms(), FatalError(), n, progressbar.example::p, and PoissonLow().
Referenced by main(), and Multinomial().
int32_t StochasticLib1::Binomial (int32_t n, double p)
Reimplemented in StochasticLib2, and StochasticLib2.
int32_t StochasticLib1::BinomialInver (int32_t n, double p) protected
int32_t StochasticLib1::BinomialInver (int32_t n, double p) protected
Definition at line 560 of file stoc1.cpp.
References n, and progressbar.example::p.
Referenced by Binomial().
int32_t StochasticLib1::BinomialRatioOfUniforms (int32_t n, double p) protected
Definition at line 605 of file stoc1.cpp.
References bino_a, bino_bound, bino_g, bino_h, bino_mode, bino_n_last, bino_p_last, bino_r1, LnFac(), n, progressbar.example::p, SHAT1, and SHAT2.
Referenced by Binomial().
int32_t StochasticLib1::BinomialRatioOfUniforms (int32_t n, double p) protected
double StochasticLib1::fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n) static protected
Definition at line 299 of file stoc1.cpp.
References LnFac().
Referenced by StochasticLib3::FishersNCHypRatioOfUnifoms(), StochasticLib2::HypPatchwork(), and HypRatioOfUnifoms().
static double StochasticLib1::fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n) static protected
int32_t StochasticLib1::Hypergeometric (int32_t n, int32_t m, int32_t N)
Reimplemented in StochasticLib2, and StochasticLib2.
Definition at line 92 of file stoc1.cpp.
References FatalError(), HypInversionMod(), HypRatioOfUnifoms(), and n.
Referenced by StochasticLib3::FishersNCHyp(), main(), StochasticLib3::MultiFishersNCHyp(), MultiHypergeometric(), StochasticLib3::MultiWalleniusNCHyp(), SplitIntoGenotypes(), and StochasticLib3::WalleniusNCHyp().
int32_t StochasticLib1::Hypergeometric (int32_t n, int32_t m, int32_t N)
Reimplemented in StochasticLib2, and StochasticLib2.
int32_t StochasticLib1::HypInversionMod (int32_t n, int32_t M, int32_t N) protected
Definition at line 151 of file stoc1.cpp.
References hyp_bound, hyp_fm, hyp_m_last, hyp_mode, hyp_mp, hyp_N_last, hyp_n_last, LnFac(), n, and progressbar.example::p.
Referenced by Hypergeometric(), and StochasticLib2::Hypergeometric().
int32_t StochasticLib1::HypInversionMod (int32_t n, int32_t M, int32_t N) protected
int32_t StochasticLib1::HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N) protected
int32_t StochasticLib1::HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N) protected
Definition at line 245 of file stoc1.cpp.
References fc_lnpk(), hyp_a, hyp_bound, hyp_fm, hyp_h, hyp_m_last, hyp_n_last, hyp_N_last, n, SHAT1, and SHAT2.
Referenced by Hypergeometric().
void StochasticLib1::MultiHypergeometric (int32_t * destination, int32_t * source, int32_t n, int colors)
Definition at line 310 of file stoc1.cpp.
References colors, FatalError(), Hypergeometric(), and n.
void StochasticLib1::MultiHypergeometric (int32_t * destination, int32_t * source, int32_t n, int colors)
void StochasticLib1::Multinomial (int32_t * destination, double * source, int32_t n, int colors)
Definition at line 660 of file stoc1.cpp.
References Binomial(), colors, FatalError(), and n.
Referenced by main().
void StochasticLib1::Multinomial (int32_t * destination, double * source, int32_t n, int colors)
void StochasticLib1::Multinomial (int32_t * destination, int32_t * source, int32_t n, int colors)
Definition at line 712 of file stoc1.cpp.
References Binomial(), colors, FatalError(), n, and progressbar.example::p.
void StochasticLib1::Multinomial (int32_t * destination, int32_t * source, int32_t n, int colors)
double StochasticLib1::Normal (double m, double s)
Definition at line 79 of file kylesGaussRand.cpp.
References normal_x2, and normal_x2_valid.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), main(), and NormalTrunc().
double StochasticLib1::Normal (double m, double s)
double StochasticLib1::Normal (double m, double s)
double StochasticLib1::NormalTrunc (double m, double s, double limit)
Definition at line 100 of file kylesGaussRand.cpp.
References Normal().
Referenced by main(), simAnealOrbFuncObj::simulator(), and MCMCorbFuncObj::simulator().
double StochasticLib1::NormalTrunc (double m, double s, double limit)
double StochasticLib1::NormalTrunc (double m, double s, double limit)
int32_t StochasticLib1::Poisson (double L)
Reimplemented in StochasticLib2, and StochasticLib2.
int32_t StochasticLib1::Poisson (double L)
Reimplemented in StochasticLib2, and StochasticLib2.
Definition at line 357 of file stoc1.cpp.
References FatalError(), PoissonInver(), PoissonLow(), and PoissonRatioUniforms().
Referenced by main().
int32_t StochasticLib1::PoissonInver (double L) protected
int32_t StochasticLib1::PoissonInver (double L) protected
Definition at line 432 of file stoc1.cpp.
References pois_f0, and pois_L_last.
Referenced by Poisson().
int32_t StochasticLib1::PoissonLow (double L) protected
Definition at line 411 of file stoc1.cpp.
Referenced by Binomial(), StochasticLib2::Binomial(), Poisson(), and StochasticLib2::Poisson().
int32_t StochasticLib1::PoissonLow (double L) protected
int32_t StochasticLib1::PoissonRatioUniforms (double L) protected
Definition at line 464 of file stoc1.cpp.
References LnFac(), pois_a, pois_bound, pois_f0, pois_g, pois_h, pois_L_last, SHAT1, and SHAT2.
Referenced by Poisson().
int32_t StochasticLib1::PoissonRatioUniforms (double L) protected
void StochasticLib1::Shuffle (int * list, int min, int n)
void StochasticLib1::Shuffle (int * list, int min, int n)
Definition at line 794 of file stoc1.cpp.
References n.
Referenced by main().
Member Data Documentation
double StochasticLib1::bino_a protected
Definition at line 335 of file stocc.h.
Referenced by BinomialRatioOfUniforms().
int32_t StochasticLib1::bino_bound protected
Definition at line 334 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), and BinomialRatioOfUniforms().
double StochasticLib1::bino_g protected
Definition at line 337 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), and BinomialRatioOfUniforms().
double StochasticLib1::bino_h protected
Definition at line 336 of file stocc.h.
Referenced by BinomialRatioOfUniforms().
int32_t StochasticLib1::bino_mode protected
Definition at line 333 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), and BinomialRatioOfUniforms().
int32_t StochasticLib1::bino_n_last protected
Definition at line 331 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), StochasticLib2::BinomialPatchwork(), and BinomialRatioOfUniforms().
double StochasticLib1::bino_p_last protected
Definition at line 332 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), StochasticLib2::BinomialPatchwork(), and BinomialRatioOfUniforms().
double StochasticLib1::bino_r1 protected
Definition at line 338 of file stocc.h.
Referenced by StochasticLib2::BinomialModeSearch(), and BinomialRatioOfUniforms().
double StochasticLib1::hyp_a protected
Definition at line 318 of file stocc.h.
Referenced by HypRatioOfUnifoms().
int32_t StochasticLib1::hyp_bound protected
Definition at line 317 of file stocc.h.
Referenced by HypInversionMod(), and HypRatioOfUnifoms().
double StochasticLib1::hyp_fm protected
Definition at line 320 of file stocc.h.
Referenced by HypInversionMod(), and HypRatioOfUnifoms().
double StochasticLib1::hyp_h protected
Definition at line 319 of file stocc.h.
Referenced by HypRatioOfUnifoms().
int32_t StochasticLib1::hyp_m_last protected
Definition at line 315 of file stocc.h.
Referenced by HypInversionMod(), StochasticLib2::HypPatchwork(), and HypRatioOfUnifoms().
int32_t StochasticLib1::hyp_mode protected
Definition at line 316 of file stocc.h.
Referenced by HypInversionMod().
int32_t StochasticLib1::hyp_mp protected
Definition at line 316 of file stocc.h.
Referenced by HypInversionMod().
int32_t StochasticLib1::hyp_n_last protected
Definition at line 315 of file stocc.h.
Referenced by HypInversionMod(), StochasticLib2::HypPatchwork(), and HypRatioOfUnifoms().
int32_t StochasticLib1::hyp_N_last protected
Definition at line 315 of file stocc.h.
Referenced by HypInversionMod(), StochasticLib2::HypPatchwork(), and HypRatioOfUnifoms().
double StochasticLib1::normal_x2 protected
Definition at line 27 of file kylesGaussRand.h.
Referenced by Normal().
int StochasticLib1::normal_x2_valid protected
Definition at line 27 of file kylesGaussRand.h.
Referenced by Normal(), and StochasticLib1().
double StochasticLib1::pois_a protected
Definition at line 325 of file stocc.h.
Referenced by PoissonRatioUniforms().
int32_t StochasticLib1::pois_bound protected
Definition at line 328 of file stocc.h.
Referenced by StochasticLib2::PoissonModeSearch(), and PoissonRatioUniforms().
double StochasticLib1::pois_f0 protected
Definition at line 324 of file stocc.h.
Referenced by PoissonInver(), StochasticLib2::PoissonModeSearch(), and PoissonRatioUniforms().
double StochasticLib1::pois_g protected
Definition at line 327 of file stocc.h.
Referenced by PoissonRatioUniforms().
double StochasticLib1::pois_h protected
Definition at line 326 of file stocc.h.
Referenced by PoissonRatioUniforms().
double StochasticLib1::pois_L_last protected
Definition at line 323 of file stocc.h.
Referenced by PoissonInver(), StochasticLib2::PoissonModeSearch(), StochasticLib2::PoissonPatchwork(), and PoissonRatioUniforms().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/kylesGaussRand.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/kylesGaussRand.cpp
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stoc1.cpp
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/stoc1.cpp