SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/looped_MCMCorbSimulator1.cpp File Reference
looped_MCMCorbSimulator1.cpp File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <math.h>
#include <time.h>
#include "Toolboxes/orbToolboxes.h"
#include "simAnnealOrbSimFunc.h"
#include "MCMCorbSimFunc.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 16 of file looped_MCMCorbSimulator1.cpp.
References outputDataType::a_totals, simAnealOrbFuncObj::argPeri_deg_sigma, MCMCorbFuncObj::argPeri_deg_sigma, outputDataType::argPeri_degs, simAnealOrbFuncObj::bestOrbit, MCMCorbFuncObj::bestOrbit, SimSettingsObj::chiSquaredMax, outputDataType::chiSquareds, outputDataType::data_filename, DIdataObj::dataLoadUp(), RVdataObj::dataLoadUp(), SimSettingsObj::DIdataFilename, MCMCorbFuncObj::DIdo, simAnealOrbFuncObj::DIdo, SimSettingsObj::DIonly, MCMCorbFuncObj::DIt, simAnealOrbFuncObj::DIt, simAnealOrbFuncObj::e_sigma, MCMCorbFuncObj::e_sigma, simAnealOrbFuncObj::earliestEpoch, MCMCorbFuncObj::earliestEpoch, RVdataObj::epochs_RV, outputDataType::es, simAnealOrbFuncObj::inclination_deg_sigma, MCMCorbFuncObj::inclination_deg_sigma, outputDataType::inclination_degs, simAnealOrbFuncObj::longAN_deg_sigma, MCMCorbFuncObj::longAN_deg_sigma, outputDataType::longAN_degs, RVdataObj::numEpochs_RV, SimSettingsObj::numSamplePrints, SimSettingsObj::numSamples, simAnealOrbFuncObj::numSamples_SA, outputDataType::numSamplesAccepted, BinaryOrbSimStarterDuo::numSamplesString, simAnealOrbFuncObj::ODT, MCMCorbFuncObj::ODT, MCMCorbFuncObj::paramChangeStepSizePercent, simAnealOrbFuncObj::period_sigma, MCMCorbFuncObj::period_sigma, outputDataType::periods, simAnealOrbFuncObj::randSeed, MCMCorbFuncObj::randSeed, RVdataObj::RV_inv_var, SimSettingsObj::RVdataFilename, MCMCorbFuncObj::RVdo, simAnealOrbFuncObj::RVdo, outputDataType::RVoffsets, SimSettingsObj::RVonly, RVdataObj::RVs, SimSettingsObj::settings_and_InputDataDir, SimSettingsObj::settingsLoadUp(), simAnealOrbFuncObj::sigmaPercent, MCMCorbFuncObj::sigmaPercent, simAnealOrbFuncObj::sigmaPercent_latest, SimSettingsObj::silent, simAnealOrbFuncObj::simulator(), MCMCorbFuncObj::simulator(), MCMCorbFuncObj::SSlogStr, simAnealOrbFuncObj::SSlogStr, MCMCorbFuncObj::SSO, simAnealOrbFuncObj::SSO, MCMCorbFuncObj::start_argPeri, MCMCorbFuncObj::start_e, MCMCorbFuncObj::start_inc_deg, MCMCorbFuncObj::start_longAN, MCMCorbFuncObj::start_offsets, MCMCorbFuncObj::start_period, MCMCorbFuncObj::start_T, simAnealOrbFuncObj::startTemp, SimSettingsObj::SystemDataFilename, DataObj::systemDataLoadUp(), simAnealOrbFuncObj::T_sigma, MCMCorbFuncObj::T_sigma, simAnealOrbFuncObj::tempStepSizePercent, outputDataType::Ts, SimSettingsObj::verbose, and DItools::verbose.