SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/mcONLYorbSimulator.cpp File Reference
mcONLYorbSimulator.cpp File Reference
#include <iostream>
#include <iomanip>
#include <limits>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <math.h>
#include <time.h>
#include "toolboxes/orbToolboxes.h"
#include "rnd/kylesGaussRand.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
This is the core C++ simulator to perform simple Monte Carlo runs. Thanks to its simplicity, unlike MCMC and Simulated Annealing, there is no C++ manager & core function structure needed.
Author:
Kyle Mede, kylem.nosp@m.ede@.nosp@m.astro.nosp@m.n.s..nosp@m.u-tok.nosp@m.yo.a.nosp@m.c.jp
Definition at line 14 of file mcONLYorbSimulator.cpp.
References semiMajorType::a1, semiMajorType::a2, RVtools::a_total, multiEpochOrbCalcReturnType::a_total, DItools::a_total, semiMajorType::a_total, SimSettingsObj::a_totalMAX, SimSettingsObj::a_totalMIN, outputDataType::a_totals, DItools::argPeri_deg, eccArgPeri2ToTcType::argPeri_deg, SimSettingsObj::argPeri_degMAX, SimSettingsObj::argPeri_degMIN, outputDataType::argPeri_degs, SimSettingsObj::argPeriOffsetDI, SimSettingsObj::argPeriOffsetRV, multiEpochOrbCalcReturnType::chi_squared_total, generalTools::chiSquaredCalc(), SimSettingsObj::chiSquaredMax, outputDataType::chiSquareds, outputDataType::data_filename, DIdataObj::dataLoadUp(), RVdataObj::dataLoadUp(), SimSettingsObj::DIdataFilename, SimSettingsObj::DIonly, generalTools::DItoolsParamLoadUp(), DItools::e, eccArgPeri2ToTcType::e, generalTools::earliestEpochFinder(), generalTools::eccArgPeri2ToTcCalc(), SimSettingsObj::eMAX, SimSettingsObj::eMIN, VRcalcStarPlanet::epochs_p, RVdataObj::epochs_RV, VRcalcStarStar::epochs_s, outputDataType::es, generalTools::fileWriter(), generalTools::findDirectory(), DItools::inclination_deg, SimSettingsObj::inclination_degMAX, SimSettingsObj::inclination_degMIN, outputDataType::inclination_degs, SimSettingsObj::K_MAX, SimSettingsObj::K_MIN, VRcalcStarPlanet::K_p, VRcalcStarStar::K_s, outputDataType::Ks, generalTools::logFileWriter(), DItools::longAN_deg, SimSettingsObj::longAN_degMAX, SimSettingsObj::longAN_degMIN, outputDataType::longAN_degs, DataObj::Mass1, DItools::Mass1, semiMajorType::Mass1, DataObj::Mass1_error, DItools::Mass2, semiMajorType::Mass2, VRcalcStarStar::multiEpochCalc(), VRcalcStarPlanet::multiEpochCalc(), DItools::multiEpochOrbCalc(), StochasticLib1::NormalTrunc(), DIdataObj::numEpochs_DI, RVdataObj::numEpochs_RV, SimSettingsObj::numSamplePrints, SimSettingsObj::numSamples, outputDataType::numSamplesAccepted, generalTools::numSamplesStringMaker(), DItools::period, semiMajorType::period, eccArgPeri2ToTcType::period, SimSettingsObj::periodMAX, SimSettingsObj::periodMIN, outputDataType::periods, PI, DataObj::planet_argPeri, DataObj::planet_e, DataObj::planet_inc, DataObj::planet_K, DataObj::planet_long_AN, DataObj::planet_MsinI, DataObj::planet_MsinI_error, DataObj::planet_P, DataObj::planet_T, DataObj::planet_Tc, RVtools::primaryStarRVs, SimSettingsObj::primaryStarRVs, RVdataObj::RV_inv_var, SimSettingsObj::RVdataFilename, SimSettingsObj::RVoffsetMAXs, SimSettingsObj::RVoffsetMINs, outputDataType::RVoffsets, SimSettingsObj::RVonly, RVdataObj::RVs, generalTools::semiMajorConverter(), SimSettingsObj::settingsLoadUp(), SimSettingsObj::silent, SimSettingsObj::simulate_StarPlanetRV, SimSettingsObj::simulate_StarStarRV, DataObj::star_argPeri, DataObj::star_e, DataObj::star_inc, DataObj::star_K, DataObj::star_long_AN, DataObj::star_Mass2, DataObj::star_Mass2_error, DataObj::star_P, DataObj::star_T, DataObj::star_Tc, DataObj::Sys_Dist_PC, DItools::Sys_Dist_PC, DataObj::Sys_Dist_PC_error, SimSettingsObj::SystemDataFilename, DataObj::systemDataLoadUp(), DItools::T, SimSettingsObj::T_Max, SimSettingsObj::T_Min, eccArgPeri2ToTcType::Tc, SimSettingsObj::TcEqualT, outputDataType::Tcs, SimSettingsObj::TcStepping, eccArgPeri2ToTcType::To, outputDataType::Ts, CRandomSFMT::UniformRandom(), RVtools::verbose, SimSettingsObj::verbose, DItools::verbose, generalTools::VRcalcStarPlanetLoadUp(), and generalTools::VRcalcStarStarLoadUp().