SMODT-documentation: toolboxes.DItoolbox Namespace Reference
toolboxes.DItoolbox Namespace Reference
Functions
def TAcalculator2
def DIdataToDict
def proposalMaxMinsCalc
def multiEpochOrbCalc
def multiEpochOrbCalc3
def orbitCalculator
def orbitCalculator2
def orbitCalculator3
def orbitCalculatorTH_I
def orbitCalculatorTH_I2
def orbitCalculatorTH_I_PP
def multiEpochOrbCalcTH_I
def multiEpochOrbCalcTH_I3
def ABCFG_MaxMins
def ABCFG_MaxMins2
def ABCFG_values
def PASAcalculator
def RADECtoSAPA
Variables
int Mass1 = 1
UP TO THIS LINE, THIS IS THE EXACT SAME AS ORBITCALCULATOR2, SO JUST CALL IT TO SAVE CODE #######.
tuple x2 = SA_arcsec_RP_model*math.cos(math.radians(PA_deg_RP_model))
tuple y2 = SA_arcsec_RP_model*math.sin(math.radians(PA_deg_RP_model))
Function Documentation
def toolboxes.DItoolbox.ABCFG_MaxMins (aMax, aMin, argPeri_radMax, argPeri_radMin, longAN_radMax, longAN_radMin, inclination_radMax, inclination_radMin)
Definition at line 1340 of file DItoolbox.py.
References toolboxes.DItoolbox.ABCFG_MaxMins2(), and toolboxes.DItoolbox.ABCFG_values().
Referenced by toolboxes.DItoolbox.multiEpochOrbCalcTH_I3().
def toolboxes.DItoolbox.ABCFG_MaxMins2 (aMax, aMin, argPeri_radMax, argPeri_radMin, longAN_radMax, longAN_radMin, inclination_radMax, inclination_radMin)
Definition at line 1374 of file DItoolbox.py.
References toolboxes.DItoolbox.ABCFG_values().
Referenced by toolboxes.DItoolbox.ABCFG_MaxMins().
def toolboxes.DItoolbox.ABCFG_values (a, argPeri_rad, longAN_rad, inclination_rad)
Definition at line 1463 of file DItoolbox.py.
Referenced by toolboxes.DItoolbox.ABCFG_MaxMins(), toolboxes.DItoolbox.ABCFG_MaxMins2(), and toolboxes.generalToolbox.orbElementTester3TH_I().
def toolboxes.DItoolbox.DIdataToDict (filename)
Data must be in the columns:
obsDate[JD]  PA[deg]  PA_error[deg]  SA[arcsec]  SA_error[arcsec]
Definition at line 167 of file DItoolbox.py.
def toolboxes.DItoolbox.multiEpochOrbCalc (SA_arcsec_measured_REALs, SA_mean_errors, PA_deg_measured_REALs, PA_mean_errors, epochs, Sys_Dist_PC, inclination_deg, longAN_deg, e, T, period, argPeri_deg, a_total = False, Mass1 = 1, Mass2 = 1, verbose = False)
USES orbitCalculator2 to compare the SA and PA values.
Note: SA_arcsec_measured_REALs, SA_mean_errors, PA_deg_measured_REALs, PA_mean_errors inputs MUST all have
      the same length.
Definition at line 256 of file DItoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.DItoolbox.multiEpochOrbCalc3(), and toolboxes.DItoolbox.orbitCalculator2().
Referenced by toolboxes.generalToolbox.orbElementTester(), toolboxes.generalToolbox.orbElementTester2(), and toolboxes.DItoolbox.proposalMaxMinsCalc().
def toolboxes.DItoolbox.multiEpochOrbCalc3 (SA_arcsec_measured_REALs, SA_mean_errors, PA_deg_measured_REALs, PA_mean_errors, epochs, Sys_Dist_PC, inclination_deg, longAN_deg, e, T, period, argPeri_deg, a_total = False, Mass1 = 1, Mass2 = 1, verbose = False)
Uses orbitCalculator3 to compare the x and y values.
Note: SA_arcsec_measured_REALs, SA_mean_errors, PA_deg_measured_REALs, PA_mean_errors inputs MUST all have
      the same length.
Definition at line 331 of file DItoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.DItoolbox.orbitCalculator(), and toolboxes.DItoolbox.orbitCalculator3().
Referenced by toolboxes.DItoolbox.multiEpochOrbCalc(), toolboxes.generalToolbox.orbElementTester3(), and toolboxes.generalToolbox.orbElementTester4().
def toolboxes.DItoolbox.multiEpochOrbCalcTH_I (e, T, A, B, C, F, G, Mass1_Msun, Mass2_Msun, Sys_Dist_PC, SAs, PAs, epochs, SA_errors, PA_errors)
Definition at line 1215 of file DItoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.DItoolbox.multiEpochOrbCalcTH_I3(), and toolboxes.DItoolbox.orbitCalculatorTH_I2().
Referenced by toolboxes.DItoolbox.orbitCalculatorTH_I_PP().
def toolboxes.DItoolbox.multiEpochOrbCalcTH_I3 (e, T, A, B, C, F, G, Mass1_Msun, Mass2_Msun, Sys_Dist_PC, SAs, PAs, epochs, SA_errors, PA_errors)
Definition at line 1262 of file DItoolbox.py.
References toolboxes.DItoolbox.ABCFG_MaxMins(), toolboxes.generalToolbox.chiSquaredCalc(), and toolboxes.DItoolbox.orbitCalculatorTH_I2().
Referenced by toolboxes.DItoolbox.multiEpochOrbCalcTH_I(), and toolboxes.generalToolbox.orbElementTester3TH_I().
def toolboxes.DItoolbox.orbitCalculator (t, Sys_Dist_PC, inclination_deg, longAN_deg, e, T, period, argPeri_deg, a_total, Mass1 = 1, Mass2 = 1, verbose = False)
This function will calculate the output orbital parameters from the inputs for a SINGLE epoch.  Use the
multiEpochOrbCalc to do this for multiple epochs at the same time.
The t and Sys_Dist_PC parameters are generally known/measured values,
while the rest are typically random numbers.
This function is designed to work as the calculator inside a Monte Carlo Simulator.
All the equations are the result of Kepler's Laws and naturally occurring symmetries of binary star systems.
Note: RP stands for Reference Plane, ie the plane that values are measured in from Earth.
      OP stands for Orbital Plane, ie in the plane that the stars are orbiting in.
Inputs:
@param t:                            = epoch of observation/image [julian date]
@type t:                             = float
@param Sys_Dist_PC:                  = measured system distance from Earth [PC]
@type Sys_Dist_PC:                   = float
@param inclination_deg:              = inclination [deg]
@type inclination_deg:               = float
@param longAN_deg:                   = Longitude of Ascending Node [deg]
@type longAN_deg:                    = float
@param e:                            = eccentricity of orbits [unitless]
@type e:                             = float
@param T:                            = Last Periapsis Epoch/time [julian date]
@type T:                             = float
@param period:                       = period of orbits [yrs]
@type period:                        = float
@param argPeri_deg:                  = Argument of Periapsis in orbital plane [deg]
@type argPeri_deg:                   = float
@param a_total:                        = Total semi-major axis of system [AU]
@type a_total:                         = float
@param Mass1:                        = Mass of primary in system [solar masses] (Default=1, means M2 is a planet)
@type Mass1:                         = float
@param Mass2:                        = Mass of the secondary in system [solar masses] (Default=1, means M2 is a planet)
@type Mass2:                         = float
@param verbose:                      = Send prints to screen? [True/False] (Default = False)
@type verbose:                       = Python boolean (True/False). Default = False
Outputs:
@param n:                            = Mean Motion [rad/yr]
@type n:                             = float
@param M_deg:                        = Mean Anomaly [deg]
@type M_deg:                         = float
@param E_latest_deg:                 = Eccentric Anomaly [deg]
@type E_latest_deg:                  = float
@param TA_deg:                       = True Anomaly [deg]
@type TA_deg:                        = float
@param Sep_Dist_AU_OP:               = Separation Distance in orbital plane [AU]
@type Sep_Dist_AU_OP:                = float
@param SA_arcsec_RP_model:           = measured Position Angle in image [deg]
@type SA_arcsec_RP_model:            = float
@param PA_deg_RP_model:              = measured Position Angle in image [deg]
@type PA_deg_RP_model:               = float
@param a1:                           = semi-major axis of M1 [AU]
@type a1:                            = float
@param a2:                           = semi-major axis of M2 [AU]
@type a2:                            = float
Definition at line 438 of file DItoolbox.py.
References toolboxes.DItoolbox.orbitCalculator2(), and toolboxes.DItoolbox.TAcalculator2().
Referenced by DItools.multiEpochOrbCalc(), and toolboxes.DItoolbox.multiEpochOrbCalc3().
def toolboxes.DItoolbox.orbitCalculator2 (t, Sys_Dist_PC, inclination_deg, longAN_deg, e, T, period, argPeri_deg, a_total = False, Mass1 = 1, Mass2 = 1, verbose = False)
This function will calculate the output orbital parameters from the inputs for a SINGLE epoch.  Use the
multiEpochOrbCalc to do this for multiple epochs at the same time.
The t and Sys_Dist_PC parameters are generally known/measured values,
while the rest are typically random numbers.
This function is designed to work as the calculator inside a Monte Carlo Simulator.
All the equations are the result of Kepler's Laws and naturally occurring symmetries of binary star systems.
Note: RP stands for Reference Plane, ie the plane that values are measured in from Earth.
      OP stands for Orbital Plane, ie in the plane that the stars are orbiting in.
Inputs:
@param t:                            = epoch of observation/image [julian date]
@type t:                             = float
@param Sys_Dist_PC:                  = measured system distance from Earth [PC]
@type Sys_Dist_PC:                   = float
@param inclination_deg:              = inclination [deg]
@type inclination_deg:               = float
@param longAN_deg:                   = Longitude of Ascending Node [deg]
@type longAN_deg:                    = float
@param e:                            = eccentricity of orbits [unitless]
@type e:                             = float
@param T:                            = Last Periapsis Epoch/time [julian date]
@type T:                             = float
@param period:                       = period of orbits [yrs]
@type period:                        = float
@param argPeri_deg:                  = Argument of Periapsis in orbital plane [deg]
@type argPeri_deg:                   = float
@param a_total:                      = Total semi-major axis of system [AU]
@type a_total:                       = float if it is to be used, boolean False if to be calculated from Kepler's 3rd
@param Mass1:                        = Mass of primary in system [kg] (Default=1, means M2 is a planet)
@type Mass1:                         = float
@param Mass2:                        = Mass of the secondary in system [kg] (Default=1, means M2 is a planet)
@type Mass2:                         = float
@param verbose:                      = Send prints to screen? [True/False] (Default = False)
@type verbose:                       = Python boolean (True/False). Default = False
Outputs:
@param n:                            = Mean Motion [rad/yr]
@type n:                             = float
@param M_deg:                        = Mean Anomaly [deg]
@type M_deg:                         = float
@param E_latest_deg:                 = Eccentric Anomaly [deg]
@type E_latest_deg:                  = float
@param TA_deg:                       = True Anomaly [deg]
@type TA_deg:                        = float
@param Sep_Dist_AU_OP:               = Separation Distance in orbital plane [AU]
@type Sep_Dist_AU_OP:                = float
@param SA_arcsec_RP_model:           = measured Position Angle in image [deg]
@type SA_arcsec_RP_model:            = float
@param PA_deg_RP_model:              = measured Position Angle in image [deg]
@type PA_deg_RP_model:               = float
@param a1:                           = semi-major axis of M1 [AU]
@type a1:                            = float
@param a2:                           = semi-major axis of M2 [AU]
@type a2:                            = float
Definition at line 618 of file DItoolbox.py.
References toolboxes.DItoolbox.orbitCalculator3(), and toolboxes.DItoolbox.TAcalculator2().
Referenced by toolboxes.generalToolbox.makeArtificialData(), toolboxes.DItoolbox.multiEpochOrbCalc(), toolboxes.DItoolbox.orbitCalculator(), and toolboxes.DItoolbox.orbitCalculator3().
def toolboxes.DItoolbox.orbitCalculator3 (t, Sys_Dist_PC, inclination_deg, longAN_deg, e, T, period, argPeri_deg, a_total = False, Mass1 = 1, Mass2 = 1, verbose = False)
This version will output the x and y values predicted for a certain epoch for comparison to measured x and y
values in the images.  If you want to compare to SA and PA, use orbitCalculator2.
This function will calculate the output orbital parameters from the inputs for a SINGLE epoch.  Use the
multiEpochOrbCalc to do this for multiple epochs at the same time.
The t and Sys_Dist_PC parameters are generally known/measured values,
while the rest are typically random numbers.
This function is designed to work as the calculator inside a Monte Carlo Simulator.
All the equations are the result of Kepler's Laws and naturally occurring symmetries of binary star systems.
Note: RP stands for Reference Plane, ie the plane that values are measured in from Earth.
      OP stands for Orbital Plane, ie in the plane that the stars are orbiting in.
Inputs:
@param t:                            = epoch of observation/image [julian date]
@type t:                             = float
@param Sys_Dist_PC:                  = measured system distance from Earth [PC]
@type Sys_Dist_PC:                   = float
@param inclination_deg:              = inclination [deg]
@type inclination_deg:               = float
@param longAN_deg:                   = Longitude of Ascending Node [deg]
@type longAN_deg:                    = float
@param e:                            = eccentricity of orbits [unitless]
@type e:                             = float
@param T:                            = Last Periapsis Epoch/time [julian date]
@type T:                             = float
@param period:                       = period of orbits [yrs]
@type period:                        = float
@param argPeri_deg:                  = Argument of Periapsis in orbital plane [deg]
@type argPeri_deg:                   = float
@param a_total:                      = Total semi-major axis of system [AU]
@type a_total:                       = float if it is to be used, boolean False if to be calculated from Kepler's 3rd
@param Mass1:                        = Mass of primary in system [kg] (Default=1, means M2 is a planet)
@type Mass1:                         = float
@param Mass2:                        = Mass of the secondary in system [kg] (Default=1, means M2 is a planet)
@type Mass2:                         = float
@param verbose:                      = Send prints to screen? [True/False] (Default = False)
@type verbose:                       = Python boolean (True/False). Default = False
Outputs:
@param n:                            = Mean Motion [rad/yr]
@type n:                             = float
@param M_deg:                        = Mean Anomaly [deg]
@type M_deg:                         = float
@param E_latest_deg:                 = Eccentric Anomaly [deg]
@type E_latest_deg:                  = float
@param TA_deg:                       = True Anomaly [deg]
@type TA_deg:                        = float
@param Sep_Dist_AU_OP:               = Separation Distance in orbital plane [AU]
@type Sep_Dist_AU_OP:                = float
@param SA_arcsec_RP_model:           = measured Position Angle in image [deg]
@type SA_arcsec_RP_model:            = float
@param PA_deg_RP_model:              = measured Position Angle in image [deg]
@type PA_deg_RP_model:               = float
@param a1:                           = semi-major axis of M1 [AU]
@type a1:                            = float
@param a2:                           = semi-major axis of M2 [AU]
@type a2:                            = float
Definition at line 867 of file DItoolbox.py.
References toolboxes.DItoolbox.orbitCalculator2().
Referenced by toolboxes.DItoolbox.multiEpochOrbCalc3(), and toolboxes.DItoolbox.orbitCalculator2().
def toolboxes.DItoolbox.orbitCalculatorTH_I (A, B, C, F, G, Mass1_Msun, Mass2_Msun, Sys_Dist_PC)
Definition at line 953 of file DItoolbox.py.
def toolboxes.DItoolbox.orbitCalculatorTH_I2 (A, B, C, F, G, Mass1_Msun, Mass2_Msun, Sys_Dist_PC)
version using ideas for calculating argPeri, longAN and a from
'The Binary Stars' by robert G. Aitken.
Definition at line 1075 of file DItoolbox.py.
Referenced by toolboxes.DItoolbox.multiEpochOrbCalcTH_I(), and toolboxes.DItoolbox.multiEpochOrbCalcTH_I3().
def toolboxes.DItoolbox.orbitCalculatorTH_I_PP (A, B, C, F, G, Mass1_Msun, Mass2_Msun, Sys_Dist_PC)
Way orbital elements are found from the Thiele-Innes constants in PP1995
Definition at line 1185 of file DItoolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalcTH_I().
def toolboxes.DItoolbox.PASAcalculator (period, t, T, e, inclination_deg, longAN_deg, argPeri_deg, Sys_Dist_PC, a2, a1 = 0, verbose = True)
This function is to predict/calculate the expected Position Angle and Separation Angle for a given set of
of orbital parameters and epoch of observation.
NOTE:
This function is capable of working for 1 or 2 body systems.  In order to use it for 2 body systems, just
set the values of a1 % a2.  For 1 body systems, ie, only one of the bodies is moving and the primary is
simply stationary at one of the foci, then leave a1=0 and use a2 for the moving body's semi-major axis value.
Inputs:
@param period:             = period of orbits [yrs]
@type period:              = float
@param t:                  = epoch of observation/image [julian date]
@type t:                   = float
@param T:                  = Last Periapsis Epoch/time [julian date]
@type T:                   = float
@param e:                  = eccentricity of orbit
@type e:                   = float
@param inclination_deg:    = orbit's inclination [degrees]
@type inclination_deg:     = float
@param longAN_deg:         = Longitude of the Ascending Node [degrees]
@type longAN_deg:          = float
@param argPeri_deg:        = Argument of periapsis [degrees]
@type argPeri_deg:         = float
@param Sys_Dist_PC:        = Distance to the system from Earth [parsec]
@type Sys_Dist_PC:         = float
@param a2:                 = Semi-major axis of body 2's orbit [AU]
@type a2:                  = float
@param a1:                 = Semi-major axis of body 1's orbit [AU]
@type a1:                  = float, default=0 indicates body 2 is only moving body in system
@param verbose:            = Show progress prints to screen?
@type verbose:             = python boolean (True/False), default=True
Outputs:
@param PA_deg_RP_model:    = Position Angle [degrees]
@type PA_deg_RP_model:     = float
@param SA_arcsec_RP_model: = Separation Angle [arcsec]
@type SA_arcsec_RP_model:  = float
Definition at line 1487 of file DItoolbox.py.
def toolboxes.DItoolbox.proposalMaxMinsCalc (latestVal, sigma, Min, Max)
Find max and min values for proposing a new random parameter value when doing MCMC.
OLD simple version:
if (A_latest+A_sigma)>=Amax:
    max = Amax
    min = A_latest-A_sigma
elif (A_latest-A_sigma)<=Amin:
    max = A_latest+A_sigma
    min = Amin
else:
    max = A_latest + A_sigma
    min = A_latest - A_sigma
Definition at line 226 of file DItoolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalc().
def toolboxes.DItoolbox.RADECtoSAPA (RA, RA_error, DEC, DEC_error)
Definition at line 1692 of file DItoolbox.py.
def toolboxes.DItoolbox.TAcalculator2 (t, e, T, period, T_center = 0, verbose = False, debug = False)
$$$ Copy of exact function from orbitToolboxDuo as something odd was hapening $$$$
This is the same as TAcalculator but with some updates to the Newton's method loop
solving the Kepler's equation found in Double Stars by Heintz.
$$$$$$$$$$$$ Later testing of the two versions will prove which is better. $$$$$$$$$$$$$
Definition at line 10 of file DItoolbox.py.
Referenced by toolboxes.DItoolbox.orbitCalculator(), and toolboxes.DItoolbox.orbitCalculator2().
Variable Documentation
int toolboxes.DItoolbox.Mass1 = 1
UP TO THIS LINE, THIS IS THE EXACT SAME AS ORBITCALCULATOR2, SO JUST CALL IT TO SAVE CODE #######.
Definition at line 936 of file DItoolbox.py.
Referenced by DItools.multiEpochOrbCalc(), DataObj.systemDataLoadUp(), VRcalcStarStar.VRcalculator(), VRcalcStarPlanet.VRcalculator(), VRcalcStarStar.VRcalculatorSemiMajorType(), and VRcalcStarStar.VRcalculatorSH().
tuple toolboxes.DItoolbox.x2 = SA_arcsec_RP_model*math.cos(math.radians(PA_deg_RP_model))
Definition at line 937 of file DItoolbox.py.
Referenced by CWalleniusNCHypergeometric.lnbico(), CFishersNCHypergeometric.lng(), main(), CWalleniusNCHypergeometric.MakeTable(), CFishersNCHypergeometric.MakeTable(), CWalleniusNCHypergeometric.mode(), CWalleniusNCHypergeometric.probability(), CFishersNCHypergeometric.probability(), CWalleniusNCHypergeometric.recursive(), StochasticLib3.WalleniusNCHypInversion(), StochasticLib3.WalleniusNCHypRatioOfUnifoms(), and StochasticLib3.WalleniusNCHypTable().
tuple toolboxes.DItoolbox.y2 = SA_arcsec_RP_model*math.sin(math.radians(PA_deg_RP_model))
Definition at line 938 of file DItoolbox.py.
Referenced by log1pow(), and pow2_1().