SMODT-documentation: toolboxes.plotToolbox Namespace Reference
toolboxes.plotToolbox Namespace Reference
Functions
def ellipse
def fixPlotBordersAndLabels
def histConverter
def histAndScatterPlotter
def histAndContourPlotter
def star
def starAndErrorPolys
def starAndErrorPolysOLD
def makeCleanSummaryPlot
def summaryPlotter2
def summaryPlotter2MCMC
def summaryPlotter2MCMCfunc
def orbElementPlotter
def orbitEllipsePlotterDuo
def mcmcProgressPlotter
def diPlotterTester
def PostSimCompleteAnalysisFunc
def rvPlotterDuo
def rvModDatasetMakerDuo
def epochsToPhases
def rvFitPlotter1Body
def singleParamReadAndPlotNEW2
def singleParamReadAndPlotNEW
def dataReadAndPlotNEW3
Variables
plt = pylab.matplotlib.pyplot
patches = pylab.matplotlib.patches
Function Documentation
def toolboxes.plotToolbox.dataReadAndPlotNEW3 (filename, plotFilename, weight = True, confLevels = True, normalize = True, drawLine = False, nu = 1, plot4x1 = False)
Master plotting function for the singleParamReadAndPlotNEW
file format must follow the 'NEW' style, ie:
longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared    timesBeenHere
All 3D data should have its chiSquared values all ready be reduced.
Definition at line 4141 of file plotToolbox.py.
References toolboxes.generalToolbox.bestOrbitFinderNEW(), toolboxes.plotToolbox.singleParamReadAndPlotNEW(), and toolboxes.generalToolbox.timeString().
def toolboxes.plotToolbox.diPlotterTester (outputDatafile = '')
Definition at line 2169 of file plotToolbox.py.
References toolboxes.generalToolbox.bestOrbitFinderNEW(), toolboxes.generalToolbox.confLevelFinderNEWdataVersion(), toolboxes.plotToolbox.histAndContourPlotter(), toolboxes.plotToolbox.orbitEllipsePlotterDuo(), and toolboxes.generalToolbox.sysDataToDict().
def toolboxes.plotToolbox.ellipse (ra, rb, ang, x0, y0, Nb = 50)
For calculating Nb x and y values that lie on an ellipse
defined using ra, rb, ang, xo and yo.
@param ra:         = Semi-Major axis length
@type ra:          = any number
@param rb:         = Semi-Minor axis length
@type rb:          = any number
@param ang:        = Angle [degrees] to plot the semi-major axis
wrt horizontal, measured from positive x-axis
@type ang:         = any number
@param x0:         = X coordinate of center of ellipse
@type xo:          = any number
@param y0:         = Y coordinate of center of ellipse
@type y0:          = any number
@param Nb:         = Number of x,y points to return
@type Nb:          = int
NOTE:
based on matlab code ellipse.m written by D.G. Long,
Brigham Young University, based on the
CIRCLES.m original
written by Peter Blattner, Institute of Microtechnology,
University of
Neuchatel, Switzerland, blattner@imt.unine.ch
Definition at line 16 of file plotToolbox.py.
def toolboxes.plotToolbox.epochsToPhases (epochs2, T_center, P_yrs, verbose = False, halfOrbit = False)
converter to change the epochs of a 1-D or 2-D array to phases.
Output dimensions of phases2 will be same as input epochs2
Definition at line 3485 of file plotToolbox.py.
References toolboxes.plotToolbox.rvFitPlotter1Body().
Referenced by toolboxes.plotToolbox.rvFitPlotter1Body(), toolboxes.plotToolbox.rvModDatasetMakerDuo(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.plotToolbox.fixPlotBordersAndLabels (plot)
This will just increase the boarder thicknesses and label sizes to look better for printing or
putting in papers.
Definition at line 56 of file plotToolbox.py.
Referenced by toolboxes.plotToolbox.histConverter(), toolboxes.plotToolbox.orbitEllipsePlotterDuo(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.plotToolbox.histAndContourPlotter (xData, yData, chiSquareds, xLabel = '', yLabel = '', plotFilename = '', xLim = False, yLim = False, show = True, save = False)
This function will create a plot with a scatter plot of the xData and yData in the middle, a horizontal histogram
of the yData on the right, and vertical histogram of the xData at the top.  This is a good way to compare the
parameter space where the two data sets have their values focus.
NOTE: xData and yData must have the same length.
@param xData:         = Data to plot on the x axis
@type xData:          = list of numbers of any type, must be same length as yData
@param yData:         = Data to plot on the y axis
@type yData:          = list of numbers of any type, must be same length as xData
@param xLabel:        = label for the x axis data
@type xLabel:         = string, default is ''
@param yLabel:        = label for the y axis data
@type yLabel:         = string, default is ''
@param plotFilename:  = name of the file to save the figure to
@type plotFilename:   = string, ensuring to include directory path if not cwd
@param xLim:          = range to limit the x axis values to
@type xLim:           = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of xData
@param yLim:          = range to limit the y axis values to
@type yLim:           = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of yData
@param show:          = show the resulting figure on the screen?
@type show:           = boolean, default is False
@param save:          = save the resulting figure?
@type save:           = boolean, default is True
Definition at line 291 of file plotToolbox.py.
Referenced by toolboxes.plotToolbox.diPlotterTester().
def toolboxes.plotToolbox.histAndScatterPlotter (xData, yData, xLabel = '', yLabel = '', plotFilename = '', xLim = False, yLim = False, show = True, save = False)
This function will create a plot with a scatter plot of the xData and yData in the middle, a horizontal histogram
of the yData on the right, and vertical histogram of the xData at the top.  This is a good way to compare the
parameter space where the two data sets have their values focus.
NOTE: xData and yData must have the same length.
@param xData:         = Data to plot on the x axis
@type xData:          = list of numbers of any type, must be same length as yData
@param yData:         = Data to plot on the y axis
@type yData:          = list of numbers of any type, must be same length as xData
@param xLabel:        = label for the x axis data
@type xLabel:         = string, default is ''
@param yLabel:        = label for the y axis data
@type yLabel:         = string, default is ''
@param plotFilename:  = name of the file to save the figure to
@type plotFilename:   = string, ensuring to include directory path if not cwd
@param xLim:          = range to limit the x axis values to
@type xLim:           = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of xData
@param yLim:          = range to limit the y axis values to
@type yLim:           = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of yData
@param show:          = show the resulting figure on the screen?
@type show:           = boolean, default is False
@param save:          = save the resulting figure?
@type save:           = boolean, default is True
Definition at line 197 of file plotToolbox.py.
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.histConverter (chiSquareds, data, plot, xlabel, confLevels = False, weight = True, normed = True, nu = 1, bestVal = 0, logY = False)
This function is for creating a modified histogram plot to be properly normalized to a max value
of 1.0.  There is also the option to color the histogram bars according to the 95 and 68% confidence
levels of the data.
Definition at line 72 of file plotToolbox.py.
References toolboxes.plotToolbox.fixPlotBordersAndLabels(), and toolboxes.generalToolbox.likelihoodsCalc().
Referenced by toolboxes.plotToolbox.summaryPlotter2().
def toolboxes.plotToolbox.makeCleanSummaryPlot (outputDataFilename = '')
This will first find the lowest chisquared for a given run,
then use readTrimWrite to trim all data that is more than 40 higher than that value.
This trimmed data file will then be plotted by summaryPlotter2.
Definition at line 510 of file plotToolbox.py.
References toolboxes.generalToolbox.dataReadTrimWriteNEW2(), toolboxes.generalToolbox.findNuFromLog(), and toolboxes.plotToolbox.summaryPlotter2().
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.mcmcProgressPlotter (filenames, rootPlotFilename, nu = 1, plot4x1 = False, TcStepping = False)
Runs on NEW data files only.
Definition at line 2120 of file plotToolbox.py.
References toolboxes.plotToolbox.summaryPlotter2MCMC().
def toolboxes.plotToolbox.orbElementPlotter (plotFileTitle, longAN_degs, es, Ts, a1s, a2s, periods, inclination_degs, argPeri_degs, Sep_Dists2, thetas2, Es2, Ms2, ns2, showPlots = False)
Definition at line 1581 of file plotToolbox.py.
References toolboxes.plotToolbox.orbitEllipsePlotterDuo().
Referenced by toolboxes.plotToolbox.summaryPlotter2MCMCfunc().
def toolboxes.plotToolbox.orbitEllipsePlotterDuo (longAN_deg, e, period, inc, argPeri_deg, a, sysDataDict, DIdataDict, xLabel = 'E ["]', yLabel = 'N ["]', plotFilename = '', xLim = False, yLim = False, show = True, telescopeView = False, To = 0, nuDI = 1)
This function will plot the resulting orbit for the input parameters.
NOTE: If a plotFilename is provided, then the resulting figure will be saved.
IN THIS VERSION the input orbital elements are to be lists, so that multiple orbits are drawn on one
plot.  The first orbit provided, that in the 0th element of the lists, will be used for the
main orbit which will get its 1/4 orbit sections marked by colored stars and other stuff.
#******** ALL THESE PARAMS SHOULD BE LISTS OF ELEMENTS ****************
@param longAN_degs     = Longitude of the Acending Node in degrees
@type longAN_deg:      = any type of number other than int
@param argPeri_deg:    = Argument of Periapsis in degrees
@type argPeri_deg:     = any type of number other than int
@param a:              = Semi-Major axis in AU
@type a:               = any type of number other than int
@param e:              = Eccentricity
@type e:               = any type of number other than int
@param inc:            = Inclination in degrees
@type inc:             = any type of number other than int
@param period:         = period of orbits [yrs]
@type period:          = float
#**********************************************************************
@param Sys_Dist_PC:    = Distance to the system from Earth [parsec]
@type Sys_Dist_PC:     = float
@param xLim:           = range to limit the x axis values to
@type xLim:            = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of
X values for points on the ellipse
+5% for white space padding
@param yLim:           = range to limit the y axis values to
@type yLim:            = tuple of two numbers of any type, (min,max)
default False indicates to use min and max of
Y values for points on the ellipse
+5% for white space padding
@param PAs:            = Position Angles in [degrees]
@type PAs:             = list of numbers, same length as SAs
@param SAs:            = Separation Angles in ["]
@type SAs:             = list of numbers, same lenght as PAs
@param sys_dist:       = Distance to System in [pc]
@type sys_dist:        = any type of number other than int
Definition at line 1669 of file plotToolbox.py.
References toolboxes.generalToolbox.findArrayMax(), toolboxes.generalToolbox.findArrayMin(), toolboxes.plotToolbox.fixPlotBordersAndLabels(), toolboxes.plotToolbox.star(), and toolboxes.plotToolbox.starAndErrorPolys().
Referenced by toolboxes.plotToolbox.diPlotterTester(), toolboxes.plotToolbox.orbElementPlotter(), and toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.PostSimCompleteAnalysisFunc (outputDatafile = '')
Definition at line 2250 of file plotToolbox.py.
References toolboxes.generalToolbox.bestOrbitFinderNEW(), toolboxes.generalToolbox.cFileToSimSettingsDict(), toolboxes.generalToolbox.dataFileCombiner(), toolboxes.generalToolbox.findNuFromLog(), toolboxes.generalToolbox.gelmanRubinStage2(), toolboxes.plotToolbox.histAndScatterPlotter(), toolboxes.plotToolbox.makeCleanSummaryPlot(), toolboxes.plotToolbox.orbitEllipsePlotterDuo(), toolboxes.generalToolbox.outputDatafileToDict(), toolboxes.plotToolbox.rvModDatasetMakerDuo(), toolboxes.plotToolbox.rvPlotterDuo(), toolboxes.plotToolbox.summaryPlotter2(), toolboxes.plotToolbox.summaryPlotter2MCMC(), and toolboxes.generalToolbox.sysDataToDict().
def toolboxes.plotToolbox.rvFitPlotter1Body (e, T_lastPeri, period, inc, argPeri_deg, a = 0.0, T_transitCenter = 0, RVoffsets = [0], plotFilename = '', show = True, plotFullOrbit = True)
create a plot for the RV data and a fit line from the best orbit data params.
NOTE: e, T, period, inc, argPeri_deg, a can all be lists,
      BUT T_center will be the same for all the orbits plotted.
Definition at line 3530 of file plotToolbox.py.
References toolboxes.generalToolbox.cFileToSimSettingsDict(), toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.plotToolbox.epochsToPhases(), toolboxes.generalToolbox.findArrayMax(), toolboxes.generalToolbox.findArrayMin(), toolboxes.generalToolbox.semiMajorConverter(), and toolboxes.generalToolbox.sysDataToDict().
Referenced by toolboxes.plotToolbox.epochsToPhases().
def toolboxes.plotToolbox.rvModDatasetMakerDuo (e, T_lastPeri, period, inc, argPeri_deg, a, sysDataDict, RVdataDict, paramSettingsDict, RVoffsets = [0], modDatasetsFilename = '', numModDatasets = 100)
create a plot for the RV data and a fit line from the best orbit data params.
NOTES:
If a star-planet system is being simulated, then the provided inclination will be used with the
planet's mass in the system data file/ provided dict, to calculate the residual vel.  If the value
in the dictionary/file is actually, please set inc=0 to tell this func to ignore it and use the file's value.
Definition at line 3073 of file plotToolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.plotToolbox.epochsToPhases(), toolboxes.generalToolbox.listRandomizer(), and toolboxes.generalToolbox.semiMajorConverter().
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.plotToolbox.rvPlotterDuo (e, T, Tc, period, inc, argPeri_deg, a, sysDataDict, RVdataDict, paramSettingsDict, K = 0, RVoffsets = [0], nuRV = 1, plotFilename = '', show = True, plotFullOrbit = True)
create a plot for the RV data and a fit line from the best orbit data params.
NOTES:
If a star-planet system is being simulated, then the provided inclination will be used with the
planet's mass in the system data file/ provided dict, to calculate the residual vel.  If the value
in the dictionary/file is actually, please set inc=0 to tell this func to ignore it and use the file's value.
Definition at line 2378 of file plotToolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.generalToolbox.eccArgPeri2ToTcCalc(), toolboxes.plotToolbox.epochsToPhases(), toolboxes.generalToolbox.findArrayMax(), toolboxes.generalToolbox.findArrayMin(), toolboxes.plotToolbox.fixPlotBordersAndLabels(), toolboxes.plotToolbox.rvModDatasetMakerDuo(), and toolboxes.generalToolbox.semiMajorConverter().
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.singleParamReadAndPlotNEW (filename, paramColNum, subPlot, numBins, weight = True, confLevels = True, normalize = True, drawLine = False, nu = 1)
This is the single column/param plotter for the new Master Hist plotter
that will call this in a loop to fill up a summary plot.  This is being
done as there are RAM issues of trying to load all the data for a particular
column and plot it all at once.  Thus, this one will load the data
only one bin of the hist at a time to be the most efficient with the RAM.
It is assumed that the chiSquareds in the data file are reduced, so the nu value will de-reduce
them to calculated proper likelihoods for weighting.
file format must follow the 'NEW' style, ie:
longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared    timesBeenHere
All filename checks will occur in the Master function and are thus not needed here.
All 3D data should have its chiSquared values all ready be reduced.
Definition at line 3888 of file plotToolbox.py.
Referenced by toolboxes.plotToolbox.dataReadAndPlotNEW3().
def toolboxes.plotToolbox.singleParamReadAndPlotNEW2 (filename, paramColNum, subPlot, numBins, weight = True, confLevels = True, normalize = True, drawLine = False, nu = 1)
This is the single column/param plotter for the new Master Hist plotter
that will call this in a loop to fill up a summary plot.  This is being
done as there are RAM issues of trying to load all the data for a particular
column and plot it all at once.  Thus, this one will load the data
only one bin of the hist at a time to be the most efficient with the RAM.
file format must follow the 'NEW' style, ie:
longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared    timesBeenHere
All filename checks will occur in the Master function and are thus not needed here.
All 3D data should have its chiSquared values all ready be reduced.
Definition at line 3824 of file plotToolbox.py.
References toolboxes.generalToolbox.confLevelFinderNEWdataVersion().
def toolboxes.plotToolbox.star (R, x0, y0, color = 'w', N = 5, thin = 0.5)
Returns an N-pointed star of size R at (x0, y0) (matplotlib patch).
NOTE: code base taken from star_patch.py in 'Beginning-Python-Visualization'
Definition at line 407 of file plotToolbox.py.
Referenced by toolboxes.plotToolbox.orbitEllipsePlotterDuo(), toolboxes.plotToolbox.starAndErrorPolys(), and toolboxes.plotToolbox.starAndErrorPolysOLD().
def toolboxes.plotToolbox.starAndErrorPolys (SAs, SAerrors, PAs, PAerrors, asConversion, transData, telescopeView = False)
Creates a rectangle patch for a given secondary star data point location.
It will return the patch.
SA in arcsec
PA in degrees
Definition at line 423 of file plotToolbox.py.
References toolboxes.plotToolbox.star().
Referenced by toolboxes.plotToolbox.orbitEllipsePlotterDuo().
def toolboxes.plotToolbox.starAndErrorPolysOLD (SAs, SAerrors, PAs, PAerrors, asConversion, transData, telescopeView = False)
Creates a rectangle patch for a given secondary star data point location.
It will return the patch.
SA in arcsec
PA in degrees
Definition at line 475 of file plotToolbox.py.
References toolboxes.plotToolbox.star().
def toolboxes.plotToolbox.summaryPlotter2 (outputDataFilename, plotFilename, weight = False, confLevels = True, normalize = True, nu = 1, plot4x1 = False, TcStepping = False)
This advanced plotting function will plot all the data in a 3x3 grid (or 3x1) on a single figure.  The data will be plotted
in histograms that can be will be normalized to a max of 1.0 and the data can be weighted if desired.  The
confidence levels of the data can be calculated and the resulting histograms will have the bars inside the
68% bin shaded as dark grey and 95% as light grey and the rest will be white.
if MCMC==True, then a matching summary plot will also be made for the parameter values vs step,
to show how it is converging with time.
Definition at line 577 of file plotToolbox.py.
References toolboxes.generalToolbox.confLevelFinderNEWdataVersion(), toolboxes.generalToolbox.findNuFromLog(), toolboxes.plotToolbox.histConverter(), and toolboxes.generalToolbox.timeString().
Referenced by toolboxes.plotToolbox.makeCleanSummaryPlot(), and toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.summaryPlotter2MCMC (outputDataFilename, plotFilename, nu = 1, plot4x1 = False, logFilename = '', TcStepping = False)
This will plot a progress plot for each varying parameter in the file.
Definition at line 1167 of file plotToolbox.py.
References toolboxes.generalToolbox.confLevelFinderNEWdataVersion(), toolboxes.plotToolbox.summaryPlotter2MCMCfunc(), and toolboxes.generalToolbox.timeString().
Referenced by toolboxes.plotToolbox.mcmcProgressPlotter(), and toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.plotToolbox.summaryPlotter2MCMCfunc (log, subPlot2, outputDataFilename, xlabel, paramColNum, xCenters, numChunks, chunkSize)
works for summaryPlotter2MCMC to do the plot for each param and reduce code doubling
Definition at line 1560 of file plotToolbox.py.
References toolboxes.generalToolbox.confLevelFinderNEWdataVersion(), and toolboxes.plotToolbox.orbElementPlotter().
Referenced by toolboxes.plotToolbox.summaryPlotter2MCMC().
Variable Documentation
toolboxes.plotToolbox.patches = pylab.matplotlib.patches
Definition at line 13 of file plotToolbox.py.
toolboxes.plotToolbox.plt = pylab.matplotlib.pyplot
Definition at line 12 of file plotToolbox.py.