SMODT-documentation: toolboxes.generalToolbox Namespace Reference
toolboxes.generalToolbox Namespace Reference
Functions
def eccArgPeri2ToTcCalc
def bestOrbitFinderNEW
def burnInCalc3
def CorrLengthCalc
def CorrLengthCalc2
def burnInCalcMultiFile
def gelmanRubinStage2
def MCMCeffectivePointsCalc
def effectivePointsCalcFunc
def burnInStripper
def chiSquaredCalc
def dataFileCombiner
def dataReaderNEW
def outputDatafileToDict
def dataReadTrimWriteNEW
def dataReadTrimWriteNEW2
def diffCalc
def confLevelFinderNEWchiSquaredVersion
def confLevelFinderNEWdataVersion
def confidenceLevelsFinderNEW
def cFileToSimSettingsDict
def sysDataToDict
def strToStr
def strToBool
def dictToFile
def findArrayMin
def findArrayMax
def findNuFromLog
def findTop20orbitsNEW
def gaussianDist
def likelihoodsCalc
def listRandomizer
def TAcalculator2
def timeString
def semiMajorConverter
def makeArtificialData
def orbElementTester
def orbElementTester2
def orbElementTester3
def orbElementTester4
def orbElementTester3TH_I
Function Documentation
def toolboxes.generalToolbox.bestOrbitFinderNEW (filename, printToScreen = True, saveToFile = True, returnAsList = False)
Just a simple function to find the parameters for the lowest chiSquared orbit in a
data file of the NEW format.
Definition at line 78 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.dataReadAndPlotNEW3(), toolboxes.plotToolbox.diPlotterTester(), and toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.generalToolbox.burnInCalc3 (chiSquareds, medianALLchains, jumpy = True)
This function will calculate the burn in length and return its value.
This can only truly be done for a proper MCMC that was started
at a random location in the parameter space, as anything else will
skew the chiSquareds trend.  ie. they will not roughly decrease as the
simulation runs and the burn in length will thus be more or less random and
useless information.
@param paramIN:    = parameter array including burn in data
@type paramIN:     = array (list) of doubles
Definition at line 159 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.burnInCalcMultiFile().
def toolboxes.generalToolbox.burnInCalcMultiFile (dataFilenames, simAnneal = True)
Definition at line 306 of file generalToolbox.py.
References toolboxes.generalToolbox.burnInCalc3(), and toolboxes.generalToolbox.dataReaderNEW().
def toolboxes.generalToolbox.burnInStripper (fullFilename, burnInLength, burnInStrippedFilename)
A function to read and strip the burn-in from a file and write
an output file with the burn-in stripped off the data.
Definition at line 743 of file generalToolbox.py.
def toolboxes.generalToolbox.cFileToSimSettingsDict (inputSettingsFile, outputSettingsFile = "")
This will load in a settings file written in the format for C++ originally
into a simulation settings dict for use in the wrapping Python start up
(and process managers).
Definition at line 1724 of file generalToolbox.py.
References toolboxes.generalToolbox.strToBool(), and toolboxes.generalToolbox.strToStr().
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc(), and toolboxes.plotToolbox.rvFitPlotter1Body().
def toolboxes.generalToolbox.chiSquaredCalc (real, error, model)
Just a simple function to calculate chi**2 for a given observed (real) with error
and experimental (model) value.
Note:
Ensure the units of both are the same.
Note2:
For cases where the error of the observation has different errors in the
positive and negative from the observed value, just input the mean of these.
Note3:
There should never be negative values input into this function for any
of the three inputs, but it has been made capable of handling those cases as well.
output: Resulting chi**2 value following
chi**2 = (obs - model)**2 / error**2
Definition at line 801 of file generalToolbox.py.
Referenced by main(), toolboxes.DItoolbox.multiEpochOrbCalc(), toolboxes.DItoolbox.multiEpochOrbCalc3(), toolboxes.DItoolbox.multiEpochOrbCalcTH_I(), toolboxes.DItoolbox.multiEpochOrbCalcTH_I3(), toolboxes.RVtoolbox.rv1bodyCalculator(), toolboxes.RVtoolbox.rv1bodyCalculator2(), toolboxes.RVtoolbox.rv2bodyCalculator3(), toolboxes.RVtoolbox.rv2bodyCalculator4(), toolboxes.plotToolbox.rvFitPlotter1Body(), toolboxes.plotToolbox.rvModDatasetMakerDuo(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.generalToolbox.confidenceLevelsFinderNEW (filename, verbose = False)
CAUTION, this was designed to be used with the outputs of 100ModDataset simulation outputs.
NOT a good function to load data from a long simulation with lots of output sets.
PURPOSE: This is to determine the errors that the mod dataset runs were designed to determine.
NOTE: This version is meant for the new headings from mcmcOrbSimUniform6
    longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared  RVoffset0...  timesBeenHere
    file format must be:
    line1: title
    line2: data headings
    line3: space delimited data
    line4: space delimited data
Definition at line 1668 of file generalToolbox.py.
References toolboxes.generalToolbox.confLevelFinderNEWdataVersion().
def toolboxes.generalToolbox.confLevelFinderNEWchiSquaredVersion (filename, columNum = False, returnData = False)
A function to find the 68.3 and 95.4% confidence levels in a given output data file's column.
return [[68.3% minimum, 68.3% maximum],[95.5% minimum, 95.5% maximum]]
columnNum must be an int.
file format must be:
    line1: title
    line2: data headings
    line3: space delimited data
    line4: space delimited data
Definition at line 1180 of file generalToolbox.py.
def toolboxes.generalToolbox.confLevelFinderNEWdataVersion (filename, columNum = False, returnData = False, returnChiSquareds = False, returnBestDataVal = False, fast = True)
A function to find the 68.3 and 95.4% confidence levels in a given output data file's column.
return [[68.3% minimum, 68.3% maximum],[95.5% minimum, 95.5% maximum]]
columnNum must be an int.
file format must be:
    line1: title
    line2: data headings
    line3: space delimited data
    line4: space delimited data
Definition at line 1323 of file generalToolbox.py.
References toolboxes.generalToolbox.timeString().
Referenced by toolboxes.generalToolbox.confidenceLevelsFinderNEW(), toolboxes.plotToolbox.diPlotterTester(), toolboxes.plotToolbox.singleParamReadAndPlotNEW2(), toolboxes.plotToolbox.summaryPlotter2(), toolboxes.plotToolbox.summaryPlotter2MCMC(), and toolboxes.plotToolbox.summaryPlotter2MCMCfunc().
def toolboxes.generalToolbox.CorrLengthCalc (paramIN)
This version uses np.std
This function will calculate the correlation length and return its value.
@param paramIN:    = parameter array after burn in data stripped
@type paramIN:     = array (list) of doubles
Definition at line 209 of file generalToolbox.py.
def toolboxes.generalToolbox.CorrLengthCalc2 (paramIN)
This version uses np.var
This function will calculate the correlation length and return its value.
@param paramIN:    = parameter array after burn in data stripped
@type paramIN:     = array (list) of doubles
Definition at line 253 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.MCMCeffectivePointsCalc().
def toolboxes.generalToolbox.dataFileCombiner (filenames, outFilename)
This function is to combine files written to disk by the dataWriter function and
combine them into one large data file.  These files must all be of the same epoch,
or all be 'input' files.
Note:
output file will have the 1st line be the same as the outFilename parameter and
the second line will be the same headers as the first file in the
filenames parameter has.
All files must have the same number of columns.
@param filenames:    = list of filenames to be put together
@type filenames:     = list of strings of form 'blahblah.txt'
@param outFilenames: = new filename for combined output file
@type outFilenames:  = string of form 'blahblahout.txt'
Definition at line 835 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.generalToolbox.dataReaderNEW (filename, column = 0)
filename must be a string of format: 'blahblah.txt'
    column = which column you want to have the data for, zero indexed.
    NOTE: This version is meant for the new headings from mcmcOrbSimUniform6
    longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared  RVoffset0...  timesBeenHere
    file format must be:
    line1: title
    line2: data headings
    line3: space delimited data
    line4: space delimited data
    .
    .
    .
Definition at line 908 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.burnInCalcMultiFile(), toolboxes.generalToolbox.MCMCeffectivePointsCalc(), and toolboxes.generalToolbox.outputDatafileToDict().
def toolboxes.generalToolbox.dataReadTrimWriteNEW (filename, chiSquareCutOff, verbose = False)
This function is ideal for the cases where your data sets are too big because of choosing a chiSquareMax that is
too big when running the simulator, resulting in large data files that are hard to load and plot.  In these cases
you can just find out what the standard range of chiSquareds are, and choose a lower cut-off to trim the volume
of data written to disk.  Just open the file and skim over the chiSquared column values to choose a new
cut-off.
These circumstances really only happen when you have a long 'daisy chain' run with rough settings, so this is
not expected to be a commonly used function.
NOTE: output files will have same name with 'chiSquare-cut-off-####' added to
      show it is the new trimmed version.
@param filename:             = filename
@type filename:              = string
@param chiSquareCutOff:      = max value of chiSquared for orbits to be written
@type chiSquareCutOff:       = any number
Definition at line 1019 of file generalToolbox.py.
def toolboxes.generalToolbox.dataReadTrimWriteNEW2 (filename, chiSquareCutOff, verbose = False)
### Same as dataReadTrimWriteNEW BUT with a inclination trimming feature that isn't really needed anymore ######
This function is ideal for the cases where your data sets are too big because of choosing a chiSquareMax that is
too big when running the simulator, resulting in large data files that are hard to load and plot.  In these cases
you can just find out what the standard range of chiSquareds are, and choose a lower cut-off to trim the volume
of data written to disk.  Just open the file and skim over the chiSquared column values to choose a new
cut-off.
These circumstances really only happen when you have a long 'daisy chain' run with rough settings, so this is
not expected to be a commonly used function.
NOTE: output files will have same name with 'chiSquare-cut-off-####' added to
      show it is the new trimmed version.
@param filename:             = filename
@type filename:              = string
@param chiSquareCutOff:      = max value of chiSquared for orbits to be written
@type chiSquareCutOff:       = any number
Definition at line 1085 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.makeCleanSummaryPlot().
def toolboxes.generalToolbox.dictToFile (d, filename)
This function will take an simple or complex/nested dictionary
and write it's values to a text file for future reference.
@param d: = dictionary to be written to file
@type d:  = standard Python dictionary, either simple or nested
(max 3 layers ie. dict inside a dict inside a dict)
Definition at line 2101 of file generalToolbox.py.
def toolboxes.generalToolbox.diffCalc (A, B)
Simply returns the difference between two numbers (floats) as a positive number (float).
Definition at line 1163 of file generalToolbox.py.
def toolboxes.generalToolbox.eccArgPeri2ToTcCalc (e, period, argPeri_deg, To, Tc = 0)
Definition at line 17 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.generalToolbox.effectivePointsCalcFunc (data)
for use by MCMCeffectivePointsCalc
Definition at line 706 of file generalToolbox.py.
def toolboxes.generalToolbox.findArrayMax (ary)
Find the minimum value inside an array up to 4D.
Definition at line 2165 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.orbitEllipsePlotterDuo(), toolboxes.plotToolbox.rvFitPlotter1Body(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.generalToolbox.findArrayMin (ary)
Find the minimum value inside an array up to 4D.
Definition at line 2137 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.orbitEllipsePlotterDuo(), toolboxes.plotToolbox.rvFitPlotter1Body(), and toolboxes.plotToolbox.rvPlotterDuo().
def toolboxes.generalToolbox.findNuFromLog (logFilename = '')
This will pull the value for 'nu' (the number of degrees of freedom) out of the log
file written by C++ as that is where nu was calculated and written.  Saves time calculating
it again in Python.
Definition at line 2194 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.makeCleanSummaryPlot(), toolboxes.plotToolbox.PostSimCompleteAnalysisFunc(), and toolboxes.plotToolbox.summaryPlotter2().
def toolboxes.generalToolbox.findTop20orbitsNEW (filename)
This function will hunt through a data file in the NEW format and display the top 20
orbits in the format that is used in the 'paramSettingsDict'.
NOTE: format of data file must be:
longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]    chiSquared    timesBeenHere
Definition at line 2229 of file generalToolbox.py.
def toolboxes.generalToolbox.gaussianDist (x, mean, variance)
Just a simple function to return the probability value of a value in a gaussian distribution.
Definition at line 2323 of file generalToolbox.py.
def toolboxes.generalToolbox.gelmanRubinStage2 (dataFilenames)
This will finalize the calculation of the Gelman-Rubin statistic
and write the results to a file in the same folder as the input files.
#Stage 1 of this is done in C++ and this one will just grab
the results for each individual chain and combine to calculate the final inter-chain
value.
Definition at line 370 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.generalToolbox.likelihoodsCalc (chiSquareds, nu = 1)
This function will convert the chiSqureds into likelihoods following
L =e^(-nu*chiSquared/2)
Definition at line 2338 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.histConverter().
def toolboxes.generalToolbox.listRandomizer (listIN, listIN2 = False)
Returns randomized version of a list.  If two lists pas
Definition at line 2351 of file generalToolbox.py.
Referenced by toolboxes.plotToolbox.rvModDatasetMakerDuo().
def toolboxes.generalToolbox.makeArtificialData (longAN_deg, e, T, Tc, period, inc, argPeri_deg, a_total, sys_dist, Mass1, Mass2, numDataPoints = 100)
Definition at line 2624 of file generalToolbox.py.
References toolboxes.DItoolbox.orbitCalculator2(), toolboxes.generalToolbox.semiMajorConverter(), and toolboxes.RVtoolbox.vrCalculatorStar2().
def toolboxes.generalToolbox.MCMCeffectivePointsCalc (dataFilenames, simAnneal = False)
This function will calculate the correlation length of each parameter in the input file(s).
If simAnneal=True, it will assume that only the last 25% of the chains are suitible for
calculating the correlation lengths.
Definition at line 488 of file generalToolbox.py.
References toolboxes.generalToolbox.CorrLengthCalc2(), and toolboxes.generalToolbox.dataReaderNEW().
def toolboxes.generalToolbox.orbElementTester (longAN_deg, e, period, inclination_deg, argPeri_deg, a_total, T)
This version is meant to be used on only the DI data and the original orbitCalculator,
not orbitCalculator2.
Use orbElementTester2 to test for 3D data.
Definition at line 2672 of file generalToolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalc().
def toolboxes.generalToolbox.orbElementTester2 (longAN_deg, e, T, period, inclination_deg, argPeri_deg, a_total, RV_origin_vel_0 = 0, RV_origin_vel_1 = 0)
This version is meant to be used on 3D (DI and RV) data located in the paramSettingsDict
and the orbitCalculator2.
Use orbElementTester to test for DI only data.
Definition at line 2758 of file generalToolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalc(), toolboxes.RVtoolbox.rv2bodyCalculator4(), and toolboxes.generalToolbox.semiMajorConverter().
def toolboxes.generalToolbox.orbElementTester3 (longAN_deg, e, T, period, inclination_deg, argPeri_deg, a_total, RV_origin_vel_0_proposed = 0, RV_origin_vel_1_proposed = 0)
This version is meant to be used on 3D (DI and RV) data located in the paramSettingsDict
and the orbitCalculator2.
Use orbElementTester to test for DI only data.
Definition at line 2870 of file generalToolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalc3(), toolboxes.RVtoolbox.rv2bodyCalculator3(), and toolboxes.generalToolbox.semiMajorConverter().
def toolboxes.generalToolbox.orbElementTester3TH_I (longAN_deg, e, T, period, inclination_deg, argPeri_deg, a_total)
This version is meant to be used on 3D (DI and RV) data located in the paramSettingsDict
and the orbitCalculator2.
Use orbElementTester to test for DI only data.
Definition at line 3140 of file generalToolbox.py.
References toolboxes.DItoolbox.ABCFG_values(), toolboxes.DItoolbox.multiEpochOrbCalcTH_I3(), toolboxes.RVtoolbox.rv2bodyCalculator3(), and toolboxes.generalToolbox.semiMajorConverter().
def toolboxes.generalToolbox.orbElementTester4 (longAN_deg, e, T, period, inclination_deg, argPeri_deg, a_total, RV_origin_vel_0_proposed = 0, RV_origin_vel_1_proposed = 0)
This version is meant to be used on RV data of single planet located in the paramSettingsDict.
Use orbElementTester to test for DI only data.
Definition at line 3000 of file generalToolbox.py.
References toolboxes.DItoolbox.multiEpochOrbCalc3(), and toolboxes.RVtoolbox.rv1bodyCalculator().
def toolboxes.generalToolbox.outputDatafileToDict (filename)
CAUTION, this was designed to be used with the outputs of 100ModDataset simulation outputs.
NOT a good function to load data from a long simulation with lots of output sets.
NOTE: This version is meant for the new headings from mcmcOrbSimUniform6
    longAN [deg]      e [N/A]       To [julian date]  period [yrs]   inclination [deg]   argPeri [deg]   a_total [AU]  chiSquared   K [m/s]  RVoffset0...  timesBeenHere
    file format must be:
    line1: title
    line2: data headings
    line3: space delimited data
    line4: space delimited data
    .
    .
    .
Definition at line 957 of file generalToolbox.py.
References toolboxes.generalToolbox.dataReaderNEW().
Referenced by toolboxes.plotToolbox.PostSimCompleteAnalysisFunc().
def toolboxes.generalToolbox.semiMajorConverter (Mass1, Mass2, a_total = 0.0, a1 = 0.0, a2 = 0.0, period = 0.0, verbose = False)
Notes:
Masses must be in same units!  Both MUST be provided for this func to work!!
Units of output semi-majors will be same as input semi-major units.
only one of the semi-majors needs to be input and the other two will be
calculate from that one.
period in years.
only set period to a non-zero value if you do not have any of the semi-majors
calculated/provided.  It will use Kepler's third law to find the a_total and
then the individual values using the mass ratio.
Definition at line 2564 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.makeArtificialData(), toolboxes.generalToolbox.orbElementTester2(), toolboxes.generalToolbox.orbElementTester3(), toolboxes.generalToolbox.orbElementTester3TH_I(), toolboxes.plotToolbox.rvFitPlotter1Body(), toolboxes.plotToolbox.rvModDatasetMakerDuo(), toolboxes.plotToolbox.rvPlotterDuo(), generalTools.VRcalcStarPlanetLoadUp(), and generalTools.VRcalcStarStarLoadUp().
def toolboxes.generalToolbox.strToBool (strIn, default)
Convert a string of with 'true','True','False' or 'false' in it into a
bool accordingly.
Definition at line 2088 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.cFileToSimSettingsDict().
def toolboxes.generalToolbox.strToStr (strIn)
To clean up a input string.  ie. remove any ", ', or \n values in the string
Definition at line 2077 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.cFileToSimSettingsDict(), and toolboxes.generalToolbox.sysDataToDict().
def toolboxes.generalToolbox.sysDataToDict (filename)
Extract needed data of the binary system from the general C++/Python data file
in the 'SimSettings_and_InputData' folder for Duo simulations.
Definition at line 1965 of file generalToolbox.py.
References toolboxes.generalToolbox.strToStr().
Referenced by toolboxes.plotToolbox.diPlotterTester(), toolboxes.plotToolbox.PostSimCompleteAnalysisFunc(), and toolboxes.plotToolbox.rvFitPlotter1Body().
def toolboxes.generalToolbox.TAcalculator2 (t, e, T, period, T_center = 0, verbose = False, debug = False)
This is the same as TAcalculator but with some updates to the Newton's method loop
solving the Kepler's equation found in Double Stars by Heintz.
$$$$$$$$$$$$ Later testing of the two versions will prove which is better. $$$$$$$$$$$$$
Definition at line 2392 of file generalToolbox.py.
def toolboxes.generalToolbox.timeString (duration)
takes a time duration in seconds and returns it in a nice string with info on number of
hours, minutes and/or seconds depending on duration.
Input: float
Output: string
Definition at line 2546 of file generalToolbox.py.
Referenced by toolboxes.generalToolbox.confLevelFinderNEWdataVersion(), toolboxes.plotToolbox.dataReadAndPlotNEW3(), main(), toolboxes.plotToolbox.summaryPlotter2(), toolboxes.plotToolbox.summaryPlotter2MCMC(), and generalTools.timeStr().