SMODT-documentation: progressbar.terminal Namespace Reference
progressbar.terminal Namespace Reference
Functions
def default
def setup
def render
Variables
list MODULE = sys.modules[__name__]
string COLORS = "BLUE GREEN CYAN RED MAGENTA YELLOW WHITE BLACK"
dictionary CONTROLS
dictionary VALUES
Function Documentation
def progressbar.terminal.default ()
Set the default attribute values
Definition at line 33 of file terminal.py.
Referenced by progressbar.terminal.render().
def progressbar.terminal.render (text)
Helper function to apply controls easily
Example:
apply("%(GREEN)s%(BOLD)stext%(NORMAL)s") -> a bold green text
Definition at line 68 of file terminal.py.
References progressbar.terminal.default(), and progressbar.terminal.setup().
def progressbar.terminal.setup ()
Set the terminal control strings
Definition at line 43 of file terminal.py.
Referenced by progressbar.terminal.render().
Variable Documentation
string progressbar.terminal.COLORS = "BLUE GREEN CYAN RED MAGENTA YELLOW WHITE BLACK"
Definition at line 16 of file terminal.py.
Referenced by CWalleniusNCHypergeometric.laplace(), and CWalleniusNCHypergeometric.search_inflect().
dictionary progressbar.terminal.CONTROLS
Initial value:
 {
     'BOL':'cr', 'UP':'cuu1', 'DOWN':'cud1', 'LEFT':'cub1', 'RIGHT':'cuf1',
     'CLEAR_SCREEN':'clear', 'CLEAR_EOL':'el', 'CLEAR_BOL':'el1',
     'CLEAR_EOS':'ed', 'BOLD':'bold', 'BLINK':'blink', 'DIM':'dim',
     'REVERSE':'rev', 'UNDERLINE':'smul', 'NORMAL':'sgr0',
     'HIDE_CURSOR':'cinvis', 'SHOW_CURSOR':'cnorm'
 }
Definition at line 18 of file terminal.py.
list progressbar.terminal.MODULE = sys.modules[__name__]
Definition at line 14 of file terminal.py.
dictionary progressbar.terminal.VALUES
Initial value:
 {
     'COLUMNS':'cols', # Width of the terminal (None for unknown)
     'LINES':'lines',  # Height of the terminal (None for unknown)
     'MAX_COLORS': 'colors',
 }
Definition at line 27 of file terminal.py.