SMODT-documentation: toolboxes.RVtoolbox Namespace Reference
toolboxes.RVtoolbox Namespace Reference
Functions
def TAcalculator2
def RVdataToDict
def rvResidualWithoutPlanetResidual
def rv1bodyCalculator
def rv1bodyCalculator2
def rv2bodyCalculator3
def rv2bodyCalculator4
def vrCalculatorPlanet
def vrCalculatorStar
def vrCalculatorStar2
Function Documentation
def toolboxes.RVtoolbox.rv1bodyCalculator (RV_epochs, RVs, RVerrors, sigma_jitter, i, p, e, T, argPeri, a, verbose = False)
This is for calculating the RV and resulting chiSquared due to a planet ONLY, thus no companion star.
Naturally this system would have a planet with mass<< primary star mass.
sigma_jitter must be the unsquared version and in units of [m/s]
i in degrees
argPeri in degrees
a in AU
T in JD
t in JD
e unitless
period in years
Definition at line 345 of file RVtoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), and toolboxes.RVtoolbox.vrCalculatorStar2().
Referenced by toolboxes.generalToolbox.orbElementTester4().
def toolboxes.RVtoolbox.rv1bodyCalculator2 (RV_epochs, RVs, RVerrors, sigma_jitter, p, e, T, argPeri, M1, M2SineI, verbose = False)
This is for calculating the RV and resulting chiSquared due to a planet ONLY, thus no companion star.
Naturally this system would have a planet with mass<< primary star mass.
sigma_jitter must be the unsquared version and in units of [m/s]
i in degrees
argPeri in degrees
a in AU
T in JD
t in JD
e unitless
period in years
Definition at line 387 of file RVtoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.RVtoolbox.rv2bodyCalculator3(), and toolboxes.RVtoolbox.vrCalculatorPlanet().
def toolboxes.RVtoolbox.rv2bodyCalculator3 (RV_epochs, RVs, RVerrors, sigma_jitter, M1, M2_c, i_c, p_c, e_c, T_c, argPeri_c, K_p, p_p, e_p, argPeri_p, T_p, verbose = False)
NOTE: This version uses the K equation with each objects mass.
    Use rv2bodyCalculator4 to use the semi-major axis instead.
This will calclulate the radial velocity residue based chiSquared considering RV data for the primary star, orbital elements
for the companion star (indicated with '_c' parameters), and some of the parameters for the planet around the primary
star's orbital elements (indicated with the '_p' parameters).
sigma_jitter must be the unsquared version and in units of [m/s]
M2SineI_c and M1 in kg
i in degrees
argPeri in degrees
a in AU
T in JD
t in JD
e unitless
period in years
Definition at line 429 of file RVtoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.RVtoolbox.rv2bodyCalculator4(), toolboxes.RVtoolbox.vrCalculatorPlanet(), and toolboxes.RVtoolbox.vrCalculatorStar().
Referenced by toolboxes.generalToolbox.orbElementTester3(), toolboxes.generalToolbox.orbElementTester3TH_I(), and toolboxes.RVtoolbox.rv1bodyCalculator2().
def toolboxes.RVtoolbox.rv2bodyCalculator4 (RV_epochs, RVs, RVerrors, sigma_jitter, M1, a1, i_c, p_c, e_c, T_c, argPeri_c, K_p, p_p, e_p, argPeri_p, T_p, verbose = False)
NOTE: This version uses the K equation with the semi-major axis instead of each objects masses.
      Use rv2bodyCalculator3 to use the objects masses instead.
This will calclulate the radial velocity residue based chiSquared considering RV data for the primary star, orbital elements
for the companion star (indicated with '_c' parameters), and some of the parameters for the planet around the primary
star's orbital elements (indicated with the '_p' parameters).
sigma_jitter must be the unsquared version and in units of [m/s]
M2SineI_c and M1 in kg
i in degrees
argPeri in degrees
a in AU
T in JD
t in JD
e unitless
period in years
Definition at line 474 of file RVtoolbox.py.
References toolboxes.generalToolbox.chiSquaredCalc(), toolboxes.RVtoolbox.vrCalculatorPlanet(), and toolboxes.RVtoolbox.vrCalculatorStar2().
Referenced by toolboxes.generalToolbox.orbElementTester2(), and toolboxes.RVtoolbox.rv2bodyCalculator3().
def toolboxes.RVtoolbox.RVdataToDict (filename)
Data must be in the columns:
obsDate[JD]  RV[m/s]  RV_error[m/s]
Jitter can be included as a 4th column value for the first line of each dataset.
These jitter values will be encorporated into the rv errors using new_err = sqrt(err**2+jitter**2)
Note: this same process takes place in the C++ code (But don't worry, it isn't done twice in a row :-P).
Spaces after rows of data indicates the end of a dataset and the following
data will be loaded as a separate dataset.
Definition at line 167 of file RVtoolbox.py.
def toolboxes.RVtoolbox.rvResidualWithoutPlanetResidual ()
A totally temporary function to calculate the residual velocity of the primary star
WITHOUT the residual from the planet.  Thus only having the velocity that could be
caused by the secondary star/companion.
Definition at line 313 of file RVtoolbox.py.
References toolboxes.RVtoolbox.vrCalculatorPlanet().
def toolboxes.RVtoolbox.TAcalculator2 (t, e, T, period, T_center = 0, verbose = False, debug = False)
$$$ Copy of exact function from orbitToolboxDuo as something odd was hapening $$$$
This is the same as TAcalculator but with some updates to the Newton's method loop
solving the Kepler's equation found in Double Stars by Heintz.
$$$$$$$$$$$$ Later testing of the two versions will prove which is better. $$$$$$$$$$$$$
Definition at line 10 of file RVtoolbox.py.
Referenced by toolboxes.RVtoolbox.vrCalculatorPlanet(), toolboxes.RVtoolbox.vrCalculatorStar(), and toolboxes.RVtoolbox.vrCalculatorStar2().
def toolboxes.RVtoolbox.vrCalculatorPlanet (t, e, T, period, argPeri, M1, T_center = 0, M2SineI = False, K = False, verbose = False)
Version for when the companion is a planet.  Thus it calculates the residual velocity
assuming this and the consequence that (M1+M2~=M1).  Returns residual velocity
of the primary star!! due to the planet, not the the vel of the planet.
M1 in Msun
M2SineI in Mjupiter
argPeri in degrees
a in AU
T in JD
t in JD
e unitless
period in days
K=False implies that the provided values will be used to
calculate it from scratch, else the provided value will
be used to calculate the radial velocity residual.  Thus,
this param must be either False or a float in units of
m/s.
returned vel will be in m/s
Definition at line 519 of file RVtoolbox.py.
References toolboxes.RVtoolbox.TAcalculator2().
Referenced by toolboxes.RVtoolbox.rv1bodyCalculator2(), toolboxes.RVtoolbox.rv2bodyCalculator3(), toolboxes.RVtoolbox.rv2bodyCalculator4(), and toolboxes.RVtoolbox.rvResidualWithoutPlanetResidual().
def toolboxes.RVtoolbox.vrCalculatorStar (t, e, T, period, argPeri, M1, M2, T_center = 0, i = False, K = False, verbose = False)
NOTE: This version is the one that uses the objects masses to calculate K.
      To use the one that calculates it using the semi-major axis, use vrCalculatorStar2.
M1 and M2 in Msun
argPeri in degrees
i in degrees
T in JD
t in JD
e unitless
period in years
K=False implies that the provided values will be used to
calculate it from scratch, else the provided value will
be used to calculate the radial velocity residule.  Thus,
this param must be either False or a float in units of
m/s.
returned vel will be in m/s
Definition at line 577 of file RVtoolbox.py.
References toolboxes.RVtoolbox.TAcalculator2().
Referenced by toolboxes.RVtoolbox.rv2bodyCalculator3().
def toolboxes.RVtoolbox.vrCalculatorStar2 (t, e, T, period, argPeri, a1, T_center = 0, i = False, K = False, verbose = False)
NOTE: this is the version which uses the K equation with the semi-major axis of primary's orbit.
      To use the masses instead, use vrCalculatorStar.
argPeri in degrees
i in degrees
T in JD
t in JD
e unitless
period in years
a1 in AU
K=False implies that the provided values will be used to
calculate it from scratch, else the provided value will
be used to calculate the radial velocity residule.  Thus,
this param must be either False or a float in units of
m/s.
returned vel will be in m/s
Definition at line 631 of file RVtoolbox.py.
References toolboxes.RVtoolbox.TAcalculator2().
Referenced by toolboxes.generalToolbox.makeArtificialData(), toolboxes.RVtoolbox.rv1bodyCalculator(), and toolboxes.RVtoolbox.rv2bodyCalculator4().