SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/testpois.cpp File Reference
testpois.cpp File Reference
#include <time.h>
#include "stocc.h"
#include "mersenne.cpp"
#include "stoc1.cpp"
#include "userintf.cpp"
Functions
int main ()
Function Documentation
int main ()
Definition at line 38 of file testpois.cpp.
References EndOfProgram(), LnFac(), StochasticLib1::Poisson(), and toolboxes.DItoolbox::x2.