SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/randomc.h File Reference
randomc.h File Reference
Macros
#define INT64_SUPPORTED
Typedefs
typedef signed int int32_t
typedef unsigned int uint32_t
typedef long long int64_t
typedef unsigned long long uint64_t
Functions
void EndOfProgram (void)
void FatalError (const char *ErrorText)
Macro Definition Documentation
#define INT64_SUPPORTED
Definition at line 122 of file randomc.h.
Typedef Documentation
typedef signed int int32_t
Definition at line 118 of file randomc.h.
typedef long long int64_t
Definition at line 120 of file randomc.h.
typedef unsigned int uint32_t
Definition at line 119 of file randomc.h.
typedef unsigned long long uint64_t
Definition at line 121 of file randomc.h.
Function Documentation
void EndOfProgram (void)
Definition at line 34 of file userintf.cpp.
Referenced by FatalError(), and main().
void FatalError (const char * ErrorText)
Definition at line 57 of file userintf.cpp.
Referenced by StochasticLib1::Bernoulli(), CWalleniusNCHypergeometric::binoexpand(), CMultiWalleniusNCHypergeometric::binoexpand(), StochasticLib1::Binomial(), StochasticLib2::Binomial(), CFishersNCHypergeometric::CFishersNCHypergeometric(), CMultiFishersNCHypergeometric::CMultiFishersNCHypergeometric(), CWalleniusNCHypergeometric::findpars(), CMultiWalleniusNCHypergeometric::findpars(), StochasticLib3::FishersNCHyp(), StochasticLib1::Hypergeometric(), StochasticLib2::Hypergeometric(), CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), LnFac(), CWalleniusNCHypergeometric::mean(), CMultiWalleniusNCHypergeometric::mean(), CMultiFishersNCHypergeometric::mean(), StochasticLib3::MultiComplWalleniusNCHyp(), StochasticLib3::MultiFishersNCHyp(), StochasticLib1::MultiHypergeometric(), StochasticLib1::Multinomial(), StochasticLib3::MultiWalleniusNCHyp(), StochasticLib1::Poisson(), StochasticLib2::Poisson(), CMultiWalleniusNCHypergeometric::probability(), CMultiFishersNCHypergeometric::probability(), CFishersNCHypergeometric::probabilityRatio(), CWalleniusNCHypergeometric::recursive(), CWalleniusNCHypergeometric::search_inflect(), CMultiWalleniusNCHypergeometric::search_inflect(), CWalleniusNCHypergeometric::SetParameters(), CMultiWalleniusNCHypergeometric::SetParameters(), and StochasticLib3::WalleniusNCHyp().