SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/stoc1.cpp File Reference
stoc1.cpp File Reference
#include "stocc.h"
Functions
double LnFac (int32_t n)
Variables
const double SHAT1 = 2.943035529371538573
const double SHAT2 = 0.8989161620588987408
Function Documentation
double LnFac (int32_t n)
Definition at line 39 of file stoc1.cpp.
Referenced by StochasticLib2::BinomialF(), StochasticLib2::BinomialModeSearch(), StochasticLib2::BinomialPatchwork(), StochasticLib1::BinomialRatioOfUniforms(), CMultiFishersNCHypergeometric::CMultiFishersNCHypergeometric(), StochasticLib1::fc_lnpk(), StochasticLib1::HypInversionMod(), CWalleniusNCHypergeometric::lnbico(), CMultiWalleniusNCHypergeometric::lnbico(), LnFacr(), CFishersNCHypergeometric::lng(), CMultiFishersNCHypergeometric::lng(), main(), StochasticLib2::PoissonF(), StochasticLib2::PoissonModeSearch(), StochasticLib2::PoissonPatchwork(), StochasticLib1::PoissonRatioUniforms(), and CWalleniusNCHypergeometric::probability().
Variable Documentation
const double SHAT1 = 2.943035529371538573
Definition at line 32 of file stoc1.cpp.
Referenced by StochasticLib1::BinomialRatioOfUniforms(), StochasticLib1::HypRatioOfUnifoms(), and StochasticLib1::PoissonRatioUniforms().
const double SHAT2 = 0.8989161620588987408
Definition at line 33 of file stoc1.cpp.
Referenced by StochasticLib1::BinomialRatioOfUniforms(), StochasticLib1::HypRatioOfUnifoms(), and StochasticLib1::PoissonRatioUniforms().