SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/sfmt.cpp File Reference
sfmt.cpp File Reference
#include "sfmt.h"
Functions
static uint32_t func1 (uint32_t x)
static uint32_t func2 (uint32_t x)
static __m128i sfmt_recursion (__m128i const &a, __m128i const &b, __m128i const &c, __m128i const &d, __m128i const &mask)
Function Documentation
static uint32_t func1 (uint32_t x) static
Definition at line 100 of file sfmt.cpp.
Referenced by CRandomSFMT::RandomInitByArray().
static uint32_t func2 (uint32_t x) static
Definition at line 104 of file sfmt.cpp.
Referenced by CRandomSFMT::RandomInitByArray().
static __m128i sfmt_recursion (__m128i const & a, __m128i const & b, __m128i const & c, __m128i const & d, __m128i const & mask) inline static
Definition at line 228 of file sfmt.cpp.
References SFMT_SL1, SFMT_SL2, SFMT_SR1, and SFMT_SR2.
Referenced by CRandomSFMT::Generate().