SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/testfnch.cpp File Reference
testfnch.cpp File Reference
#include <time.h>
#include "stocc.h"
#include "mersenne.cpp"
#include "stoc1.cpp"
#include "stoc3.cpp"
#include "fnchyppr.cpp"
#include "wnchyppr.cpp"
#include "userintf.cpp"
Functions
int main ()
Function Documentation
int main ()
Definition at line 40 of file testfnch.cpp.
References EndOfProgram(), StochasticLib3::FishersNCHyp(), CFishersNCHypergeometric::mean(), CFishersNCHypergeometric::moments(), n, CFishersNCHypergeometric::probability(), and toolboxes.DItoolbox::x2.