SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/wnchyppr.cpp File Reference
wnchyppr.cpp File Reference
#include <string.h>
#include "stocc.h"
#include "erfres.cpp"
Macros
#define IPOINTS 8
#define IPOINTS 8
Functions
double pow2_1 (double q, double *y0=0)
double log1mx (double x, double x1)
double log1pow (double q, double x)
double LnFacr (double x)
double FallingFactorial (double a, double b)
double Erf (double x)
int32_t FloorLog2 (float x)
int NumSD (double accuracy)
Variables
static const double LN2 = 0.693147180559945309417
Macro Definition Documentation
#define IPOINTS 8
Referenced by CWalleniusNCHypergeometric::integrate_step(), and CMultiWalleniusNCHypergeometric::integrate_step().
#define IPOINTS 8
Function Documentation
double Erf (double x)
Definition at line 240 of file wnchyppr.cpp.
References Erf(), n, rsqrtpi, and rsqrtpi2.
double FallingFactorial (double a, double b)
Definition at line 209 of file wnchyppr.cpp.
int32_t FloorLog2 (float x)
Definition at line 279 of file wnchyppr.cpp.
double LnFacr (double x)
Definition at line 187 of file wnchyppr.cpp.
double log1mx (double x, double x1)
Definition at line 129 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), CWalleniusNCHypergeometric::laplace(), and CMultiWalleniusNCHypergeometric::laplace().
double log1pow (double q, double x)
Definition at line 148 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), CWalleniusNCHypergeometric::integrate_step(), and CMultiWalleniusNCHypergeometric::integrate_step().
int NumSD (double accuracy)
Definition at line 303 of file wnchyppr.cpp.
double pow2_1 (double q, double * y0 = 0)
Definition at line 106 of file wnchyppr.cpp.
References LN2.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), CWalleniusNCHypergeometric::findpars(), CMultiWalleniusNCHypergeometric::findpars(), CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::mean(), CWalleniusNCHypergeometric::search_inflect(), and CMultiWalleniusNCHypergeometric::search_inflect().
Variable Documentation
const double LN2 = 0.693147180559945309417 static
Definition at line 34 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), CWalleniusNCHypergeometric::findpars(), CMultiWalleniusNCHypergeometric::findpars(), FloorLog2(), CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::mean(), pow2_1(), CWalleniusNCHypergeometric::search_inflect(), and CMultiWalleniusNCHypergeometric::search_inflect().