SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stocc.h File Reference
stocc.h File Reference
#include <math.h>
#include "randomc.h"
Classes
class StochasticLib1
class StochasticLib2
class StochasticLib3
class CWalleniusNCHypergeometric
class CMultiWalleniusNCHypergeometric
class CMultiWalleniusNCHypergeometricMoments
class CFishersNCHypergeometric
class CMultiFishersNCHypergeometric
Macros
#define STOC_BASE CRandomMersenne
#define MAXCOLORS 32
#define WALL_TABLELENGTH 512
Functions
double LnFac (int32_t n)
double LnFacr (double x)
double FallingFactorial (double a, double b)
double Erf (double x)
int32_t FloorLog2 (float x)
int NumSD (double accuracy)
Variables
static const int FAK_LEN = 1024
static const int ERFRES_B = 16
static const int ERFRES_E = 40
static const int ERFRES_S = 2
static const int ERFRES_N = (ERFRES_E-ERFRES_B)/ERFRES_S+1
static const int ERFRES_L = 48
double ErfRes [ERFRES_N][ERFRES_L]
double NumSDev [ERFRES_N]
Macro Definition Documentation
#define MAXCOLORS 32
Definition at line 249 of file stocc.h.
Referenced by CMultiWalleniusNCHypergeometric::findpars(), CMultiWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::mean(), StochasticLib3::MultiComplWalleniusNCHyp(), StochasticLib3::MultiFishersNCHyp(), StochasticLib3::MultiWalleniusNCHyp(), CMultiWalleniusNCHypergeometric::search_inflect(), and CMultiFishersNCHypergeometric::variance().
#define STOC_BASE CRandomMersenne
Definition at line 217 of file stocc.h.
#define WALL_TABLELENGTH 512
Definition at line 434 of file stocc.h.
Referenced by StochasticLib3::WalleniusNCHypTable().
Function Documentation
double Erf (double x)
Definition at line 69 of file erfresmk.cpp.
double FallingFactorial (double a, double b)
Definition at line 209 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::binoexpand(), CMultiWalleniusNCHypergeometric::binoexpand(), and CFishersNCHypergeometric::probabilityRatio().
int32_t FloorLog2 (float x)
Definition at line 279 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::laplace(), and CMultiWalleniusNCHypergeometric::laplace().
double LnFac (int32_t n)
Definition at line 39 of file stoc1.cpp.
double LnFacr (double x)
Definition at line 187 of file wnchyppr.cpp.
Referenced by FallingFactorial().
int NumSD (double accuracy)
Definition at line 303 of file wnchyppr.cpp.
Referenced by CWalleniusNCHypergeometric::MakeTable(), and CFishersNCHypergeometric::MakeTable().
Variable Documentation
double ErfRes[ERFRES_N][ERFRES_L]
Definition at line 271 of file stocc.h.
const int ERFRES_B = 16 static
Definition at line 264 of file stocc.h.
Referenced by CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), and main().
const int ERFRES_E = 40 static
Definition at line 265 of file stocc.h.
Referenced by main().
const int ERFRES_L = 48 static
Definition at line 268 of file stocc.h.
Referenced by CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), and main().
const int ERFRES_N = (ERFRES_E-ERFRES_B)/ERFRES_S+1 static
Definition at line 267 of file stocc.h.
Referenced by CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), and main().
const int ERFRES_S = 2 static
Definition at line 266 of file stocc.h.
Referenced by CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), and main().
const int FAK_LEN = 1024 static
Definition at line 253 of file stocc.h.
Referenced by CWalleniusNCHypergeometric::lnbico(), LnFac(), and CFishersNCHypergeometric::lng().
double NumSDev[ERFRES_N]
Definition at line 274 of file stocc.h.