SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/rnd/ex-evol2.cpp File Reference
ex-evol2.cpp File Reference
#include <time.h>
#include "randomc.h"
#include "mersenne.cpp"
#include "stocc.h"
#include "stoc1.cpp"
#include "userintf.cpp"
Functions
void SplitIntoGenotypes (int32_t *genotypes, int32_t *genes, StochasticLib1 &stoc)
int BreedingSuccess (double *ChildGenotypes, int32_t *FathersGenotypes, int32_t *MothersGenotypes, double *Selection, int Mul)
int main ()
Function Documentation
int BreedingSuccess (double * ChildGenotypes, int32_t * FathersGenotypes, int32_t * MothersGenotypes, double * Selection, int Mul)
Definition at line 69 of file ex-evol2.cpp.
Referenced by main().
int main ()
Definition at line 141 of file ex-evol2.cpp.
References StochasticLib1::Binomial(), BreedingSuccess(), EndOfProgram(), StochasticLib1::Multinomial(), StochasticLib1::Normal(), StochasticLib1::Poisson(), and SplitIntoGenotypes().
void SplitIntoGenotypes (int32_t * genotypes, int32_t * genes, StochasticLib1 & stoc)
Definition at line 48 of file ex-evol2.cpp.
References StochasticLib1::Hypergeometric().