SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/userintf.cpp File Reference
userintf.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
Functions
void EndOfProgram ()
void FatalError (const char *ErrorText)
Function Documentation
void EndOfProgram (void)
Definition at line 34 of file userintf.cpp.
Referenced by FatalError(), and main().
void FatalError (const char * ErrorText)
Definition at line 57 of file userintf.cpp.
References EndOfProgram().
Referenced by StochasticLib1::Bernoulli(), CWalleniusNCHypergeometric::binoexpand(), CMultiWalleniusNCHypergeometric::binoexpand(), StochasticLib1::Binomial(), StochasticLib2::Binomial(), CFishersNCHypergeometric::CFishersNCHypergeometric(), CMultiFishersNCHypergeometric::CMultiFishersNCHypergeometric(), CWalleniusNCHypergeometric::findpars(), CMultiWalleniusNCHypergeometric::findpars(), StochasticLib3::FishersNCHyp(), StochasticLib1::Hypergeometric(), StochasticLib2::Hypergeometric(), CWalleniusNCHypergeometric::laplace(), CMultiWalleniusNCHypergeometric::laplace(), LnFac(), CWalleniusNCHypergeometric::mean(), CMultiWalleniusNCHypergeometric::mean(), CMultiFishersNCHypergeometric::mean(), StochasticLib3::MultiComplWalleniusNCHyp(), StochasticLib3::MultiFishersNCHyp(), StochasticLib1::MultiHypergeometric(), StochasticLib1::Multinomial(), StochasticLib3::MultiWalleniusNCHyp(), StochasticLib1::Poisson(), StochasticLib2::Poisson(), CMultiWalleniusNCHypergeometric::probability(), CMultiFishersNCHypergeometric::probability(), CFishersNCHypergeometric::probabilityRatio(), CWalleniusNCHypergeometric::recursive(), CWalleniusNCHypergeometric::search_inflect(), CMultiWalleniusNCHypergeometric::search_inflect(), CWalleniusNCHypergeometric::SetParameters(), CMultiWalleniusNCHypergeometric::SetParameters(), and StochasticLib3::WalleniusNCHyp().