SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/testmwnc.cpp File Reference
testmwnc.cpp File Reference
#include <time.h>
#include <string.h>
#include "stocc.h"
#include "mersenne.cpp"
#include "stoc1.cpp"
#include "stoc3.cpp"
#include "fnchyppr.cpp"
#include "wnchyppr.cpp"
#include "userintf.cpp"
Functions
int main ()
Variables
const int colors = 4
int32_t n = 100
int32_t mlist []
double wlist []
int32_t nsamp = 100000
Function Documentation
int main ()
Definition at line 71 of file testmwnc.cpp.
References colors, EndOfProgram(), CMultiWalleniusNCHypergeometric::mean(), mlist, CMultiWalleniusNCHypergeometricMoments::moments(), StochasticLib3::MultiWalleniusNCHyp(), n, nsamp, and wlist.
Variable Documentation
const int colors = 4
Definition at line 54 of file testmwnc.cpp.
int32_t mlist[]
Initial value:
  {30, 60, 50, 20}
Definition at line 58 of file testmwnc.cpp.
int32_t n = 100
Definition at line 56 of file testmwnc.cpp.
int32_t nsamp = 100000
Definition at line 64 of file testmwnc.cpp.
double wlist[]
Initial value:
  {1, 5, 3, 6}
Definition at line 61 of file testmwnc.cpp.