SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/testmfnc.cpp File Reference
testmfnc.cpp File Reference
#include <time.h>
#include <string.h>
#include "stocc.h"
#include "mersenne.cpp"
#include "stoc1.cpp"
#include "stoc3.cpp"
#include "fnchyppr.cpp"
#include "wnchyppr.cpp"
#include "userintf.cpp"
Functions
int main ()
Variables
const int colors = 4
int32_t n = 100
int32_t mlist []
double wlist []
int32_t nsamp = 10000
Function Documentation
int main ()
Definition at line 72 of file testmfnc.cpp.
References colors, EndOfProgram(), CMultiFishersNCHypergeometric::mean(), mlist, CMultiFishersNCHypergeometric::moments(), StochasticLib3::MultiFishersNCHyp(), n, nsamp, CMultiFishersNCHypergeometric::variance(), and wlist.
Variable Documentation
const int colors = 4
Definition at line 55 of file testmfnc.cpp.
int32_t mlist[]
Initial value:
{50, 30, 50, 80}
Definition at line 59 of file testmfnc.cpp.
int32_t n = 100
Definition at line 57 of file testmfnc.cpp.
int32_t nsamp = 10000
Definition at line 65 of file testmfnc.cpp.
double wlist[]
Initial value:
{1, 6, 3, 2}
Definition at line 62 of file testmfnc.cpp.