SMODT-documentation: /mnt/Data1/Todai_Work/Dropbox/workspace/SMODT/code/cppSide/toolboxes/rnd/stocc.h File Reference
stocc.h File Reference
#include <math.h>
#include "randomc.h"
Classes
class StochasticLib1
class StochasticLib2
class StochasticLib3
class CWalleniusNCHypergeometric
class CMultiWalleniusNCHypergeometric
class CMultiWalleniusNCHypergeometricMoments
class CFishersNCHypergeometric
class CMultiFishersNCHypergeometric
Macros
#define STOC_BASE CRandomMersenne
#define MAXCOLORS 32
#define WALL_TABLELENGTH 512
Functions
double LnFac (int32_t n)
double LnFacr (double x)
double FallingFactorial (double a, double b)
double Erf (double x)
int32_t FloorLog2 (float x)
int NumSD (double accuracy)
Variables
static const int FAK_LEN = 1024
static const int ERFRES_B = 16
static const int ERFRES_E = 40
static const int ERFRES_S = 2
static const int ERFRES_N = (ERFRES_E-ERFRES_B)/ERFRES_S+1
static const int ERFRES_L = 48
double ErfRes [ERFRES_N][ERFRES_L]
double NumSDev [ERFRES_N]
Macro Definition Documentation
#define MAXCOLORS 32
Definition at line 249 of file stocc.h.
#define STOC_BASE CRandomMersenne
Definition at line 217 of file stocc.h.
#define WALL_TABLELENGTH 512
Definition at line 434 of file stocc.h.
Function Documentation
double Erf (double x)
Definition at line 69 of file erfresmk.cpp.
References Erf(), n, rsqrtpi, and rsqrtpi2.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), Erf(), and ErfC().
double FallingFactorial (double a, double b)
Definition at line 209 of file wnchyppr.cpp.
References LnFacr(), and n.
int32_t FloorLog2 (float x)
Definition at line 279 of file wnchyppr.cpp.
References LN2, and n.
double LnFac (int32_t n)
Definition at line 39 of file stoc1.cpp.
References FAK_LEN, FatalError(), and n.
Referenced by StochasticLib2::BinomialF(), StochasticLib2::BinomialModeSearch(), StochasticLib2::BinomialPatchwork(), StochasticLib1::BinomialRatioOfUniforms(), CMultiFishersNCHypergeometric::CMultiFishersNCHypergeometric(), StochasticLib1::fc_lnpk(), StochasticLib1::HypInversionMod(), CWalleniusNCHypergeometric::lnbico(), CMultiWalleniusNCHypergeometric::lnbico(), LnFacr(), CFishersNCHypergeometric::lng(), CMultiFishersNCHypergeometric::lng(), main(), StochasticLib2::PoissonF(), StochasticLib2::PoissonModeSearch(), StochasticLib2::PoissonPatchwork(), StochasticLib1::PoissonRatioUniforms(), and CWalleniusNCHypergeometric::probability().
double LnFacr (double x)
Definition at line 187 of file wnchyppr.cpp.
References LnFac().
int NumSD (double accuracy)
Definition at line 303 of file wnchyppr.cpp.
Variable Documentation
double ErfRes[ERFRES_N][ERFRES_L]
Definition at line 271 of file stocc.h.
const int ERFRES_B = 16 static
Definition at line 264 of file stocc.h.
const int ERFRES_E = 40 static
Definition at line 265 of file stocc.h.
const int ERFRES_L = 48 static
Definition at line 268 of file stocc.h.
const int ERFRES_N = (ERFRES_E-ERFRES_B)/ERFRES_S+1 static
Definition at line 267 of file stocc.h.
const int ERFRES_S = 2 static
Definition at line 266 of file stocc.h.
const int FAK_LEN = 1024 static
Definition at line 253 of file stocc.h.
double NumSDev[ERFRES_N]
Definition at line 274 of file stocc.h.