SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/MCMCorbSimulator.cpp File Reference
MCMCorbSimulator.cpp File Reference
#include <iostream>
#include <iomanip>
#include <limits>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <fstream>
#include <math.h>
#include <time.h>
#include "toolboxes/orbToolboxes.h"
#include "simAnnealOrbSimFunc.h"
#include "MCMCorbSimFunc.h"
Functions
int main (int argc, char *argv[])
Detailed Description
This is a bunch of test documentation.
Author:
: Kyle Mede, kylem.nosp@m.ede@.nosp@m.astro.nosp@m.n.s..nosp@m.u-tok.nosp@m.yo.a.nosp@m.c.jp /*!
Definition in file MCMCorbSimulator.cpp.
Function Documentation
int main (int argc, char * argv[])
This is the "main" that performs the MCMC process for a single chain of a multi or single chain/thread/process MCMC simulation started by the Python file BinaryOrbSimStarterDuo.py and controlled with the MCMC_ProcessManagerDuo. It will perform the set up tasks, call the simAnnealOrbSimFunc and MCMCorbSimFunc to perform the Simulated Annealing and MCMC stages for the chain based on the input settings. After the MCMC process is complete it will perform the requested wrap up and statistical calculations requested then write all the output files to disk for the wrap up tasks and plotting done by Python after all the chains are complete. The
Author:
Kyle Mede, kylem.nosp@m.ede@.nosp@m.astro.nosp@m.n.s..nosp@m.u-tok.nosp@m.yo.a.nosp@m.c.jp
Definition at line 19 of file MCMCorbSimulator.cpp.
References simAnealOrbFuncObj::a_total_sigma, MCMCorbFuncObj::a_total_sigma, SimSettingsObj::a_totalMAX, SimSettingsObj::a_totalMIN, outputDataType::a_totals, simAnealOrbFuncObj::argPeri_deg_sigma, MCMCorbFuncObj::argPeri_deg_sigma, SimSettingsObj::argPeri_degMAX, SimSettingsObj::argPeri_degMIN, outputDataType::argPeri_degs, simAnealOrbFuncObj::bestOrbit, MCMCorbFuncObj::bestOrbit, SimSettingsObj::calcCorrLengths, SimSettingsObj::CalcGelmanRubin, SimSettingsObj::chiSquaredMax, MCMCorbFuncObj::chiSquaredMin, simAnealOrbFuncObj::chiSquaredMin, outputDataType::chiSquareds, generalTools::CorrelationLengthCalc(), outputDataType::data_filename, DIdataObj::dataLoadUp(), RVdataObj::dataLoadUp(), SimSettingsObj::DIdataFilename, MCMCorbFuncObj::DIdo, simAnealOrbFuncObj::DIdo, SimSettingsObj::DIonly, MCMCorbFuncObj::DIt, simAnealOrbFuncObj::DIt, generalTools::DItoolsParamLoadUp(), simAnealOrbFuncObj::e_sigma, MCMCorbFuncObj::e_sigma, MCMCorbFuncObj::earliestEpoch, simAnealOrbFuncObj::earliestEpoch, generalTools::earliestEpochFinder(), SimSettingsObj::eMAX, SimSettingsObj::eMIN, outputDataType::es, generalTools::filenamePrepend(), generalTools::fileWriter(), generalTools::findDirectory(), generalTools::gelmanRubinStage1(), simAnealOrbFuncObj::inclination_deg_sigma, MCMCorbFuncObj::inclination_deg_sigma, SimSettingsObj::inclination_degMAX, SimSettingsObj::inclination_degMIN, outputDataType::inclination_degs, SimSettingsObj::K_MAX, SimSettingsObj::K_MIN, simAnealOrbFuncObj::K_sigma, MCMCorbFuncObj::K_sigma, outputDataType::Ks, generalTools::logFileWriter(), simAnealOrbFuncObj::longAN_deg_sigma, MCMCorbFuncObj::longAN_deg_sigma, SimSettingsObj::longAN_degMAX, SimSettingsObj::longAN_degMIN, outputDataType::longAN_degs, MCMCorbFuncObj::numDIparams, simAnealOrbFuncObj::numDIparams, MCMCorbFuncObj::numParams, simAnealOrbFuncObj::numParams, MCMCorbFuncObj::numRVparams, simAnealOrbFuncObj::numRVparams, SimSettingsObj::numSamplePrints, SimSettingsObj::numSamples, simAnealOrbFuncObj::numSamples_SA, SimSettingsObj::numSamples_SimAnneal, outputDataType::numSamplesAccepted, generalTools::numSamplesStringMaker(), SimSettingsObj::numTimesCalcGR, MCMCorbFuncObj::ODT, simAnealOrbFuncObj::ODT, simAnealOrbFuncObj::offset_sigmas, MCMCorbFuncObj::offset_sigmas, MCMCorbFuncObj::one_over_nu_DI, simAnealOrbFuncObj::one_over_nu_DI, MCMCorbFuncObj::one_over_nu_RV, simAnealOrbFuncObj::one_over_nu_RV, MCMCorbFuncObj::one_over_nu_TOTAL, simAnealOrbFuncObj::one_over_nu_TOTAL, MCMCorbFuncObj::paramChangeStepSizePercent, simAnealOrbFuncObj::paramsToVaryIntsAry, MCMCorbFuncObj::paramsToVaryIntsAry, simAnealOrbFuncObj::period_sigma, MCMCorbFuncObj::period_sigma, SimSettingsObj::periodMAX, SimSettingsObj::periodMIN, outputDataType::periods, MCMCorbFuncObj::randSeed, simAnealOrbFuncObj::randSeed, SimSettingsObj::RVdataFilename, MCMCorbFuncObj::RVdo, simAnealOrbFuncObj::RVdo, SimSettingsObj::RVoffsetMAXs, SimSettingsObj::RVoffsetMINs, outputDataType::RVoffsets, SimSettingsObj::RVonly, MCMCorbFuncObj::saveEachInt, simAnealOrbFuncObj::saveEachInt, SimSettingsObj::settingsLoadUp(), simAnealOrbFuncObj::sigmaPercent, MCMCorbFuncObj::sigmaPercent, simAnealOrbFuncObj::sigmaPercent_latest, SimSettingsObj::silent, simAnealOrbFuncObj::simulator(), MCMCorbFuncObj::simulator(), simAnealOrbFuncObj::sqrtECosomega_sigma, MCMCorbFuncObj::sqrtECosomega_sigma, simAnealOrbFuncObj::sqrtESinomega_sigma, MCMCorbFuncObj::sqrtESinomega_sigma, MCMCorbFuncObj::SSlogStr, simAnealOrbFuncObj::SSlogStr, MCMCorbFuncObj::SSO, simAnealOrbFuncObj::SSO, MCMCorbFuncObj::start_a_total, MCMCorbFuncObj::start_argPeri, MCMCorbFuncObj::start_e, MCMCorbFuncObj::start_inc_deg, MCMCorbFuncObj::start_K, MCMCorbFuncObj::start_longAN, MCMCorbFuncObj::start_offsets, MCMCorbFuncObj::start_period, MCMCorbFuncObj::start_T, MCMCorbFuncObj::start_Tc, SimSettingsObj::startTemp, simAnealOrbFuncObj::startTemp, MCMCorbFuncObj::SYSdo, simAnealOrbFuncObj::SYSdo, SimSettingsObj::SystemDataFilename, DataObj::systemDataLoadUp(), SimSettingsObj::T_Max, SimSettingsObj::T_Min, simAnealOrbFuncObj::T_sigma, MCMCorbFuncObj::T_sigma, outputDataType::Tcs, simAnealOrbFuncObj::tempStepSizePercent, generalTools::timeStr(), toolboxes.generalToolbox::timeString(), simAnealOrbFuncObj::TMAX, MCMCorbFuncObj::TMAX, simAnealOrbFuncObj::TMIN, MCMCorbFuncObj::TMIN, outputDataType::Ts, SimSettingsObj::useMultiProcessing, simAnealOrbFuncObj::vary_K, MCMCorbFuncObj::vary_K, SimSettingsObj::verbose, and DItools::verbose.