SMODT-documentation: CMultiWalleniusNCHypergeometric Class Reference
CMultiWalleniusNCHypergeometric Class Reference
#include <stocc.h>
Public Member Functions
CMultiWalleniusNCHypergeometric (int32_t n, int32_t *m, double *odds, int colors, double accuracy=1.E-8)
void SetParameters (int32_t n, int32_t *m, double *odds, int colors)
double probability (int32_t *x)
void mean (double *mu)
CMultiWalleniusNCHypergeometric (int32_t n, int32_t *m, double *odds, int colors, double accuracy=1.E-8)
void SetParameters (int32_t n, int32_t *m, double *odds, int colors)
double probability (int32_t *x)
void mean (double *mu)
Protected Member Functions
double binoexpand (void)
double laplace (void)
double integrate (void)
double lnbico (void)
void findpars (void)
double integrate_step (double a, double b)
double search_inflect (double t_from, double t_to)
double binoexpand (void)
double laplace (void)
double integrate (void)
double lnbico (void)
void findpars (void)
double integrate_step (double a, double b)
double search_inflect (double t_from, double t_to)
Protected Attributes
double * omega
double accuracy
int32_t n
int32_t N
int32_t * m
int32_t * x
int colors
int Dummy_align
double r
double rd
double w
double wr
double E
double phi2d
double bico
Detailed Description
Definition at line 490 of file stocc.h.
Constructor & Destructor Documentation
CMultiWalleniusNCHypergeometric::CMultiWalleniusNCHypergeometric (int32_t n, int32_t * m, double * odds, int colors, double accuracy = 1.E-8)
Definition at line 1313 of file wnchyppr.cpp.
References accuracy, and SetParameters().
CMultiWalleniusNCHypergeometric::CMultiWalleniusNCHypergeometric (int32_t n, int32_t * m, double * odds, int colors, double accuracy = 1.E-8)
Member Function Documentation
double CMultiWalleniusNCHypergeometric::binoexpand (void) protected
Definition at line 1388 of file wnchyppr.cpp.
References colors, FallingFactorial(), FatalError(), m, n, and omega.
Referenced by probability().
double CMultiWalleniusNCHypergeometric::binoexpand (void) protected
void CMultiWalleniusNCHypergeometric::findpars (void) protected
Definition at line 1417 of file wnchyppr.cpp.
References colors, E, FatalError(), LN2, m, MAXCOLORS, omega, phi2d, pow2_1(), r, rd, w, and wr.
Referenced by probability().
void CMultiWalleniusNCHypergeometric::findpars (void) protected
double CMultiWalleniusNCHypergeometric::integrate (void) protected
double CMultiWalleniusNCHypergeometric::integrate (void) protected
Definition at line 1640 of file wnchyppr.cpp.
References accuracy, E, integrate_step(), lnbico(), rd, search_inflect(), and w.
Referenced by probability().
double CMultiWalleniusNCHypergeometric::integrate_step (double a, double b) protected
Definition at line 1715 of file wnchyppr.cpp.
References bico, colors, IPOINTS, log1pow(), omega, r, and rd.
Referenced by integrate().
double CMultiWalleniusNCHypergeometric::integrate_step (double a, double b) protected
double CMultiWalleniusNCHypergeometric::laplace (void) protected
Definition at line 1491 of file wnchyppr.cpp.
References accuracy, colors, ErfRes, ERFRES_B, ERFRES_L, ERFRES_N, ERFRES_S, FatalError(), FloorLog2(), LN2, lnbico(), log1mx(), MAXCOLORS, NumSDev, omega, phi2d, pow2_1(), r, rd, and w.
Referenced by probability().
double CMultiWalleniusNCHypergeometric::laplace (void) protected
double CMultiWalleniusNCHypergeometric::lnbico (void) protected
double CMultiWalleniusNCHypergeometric::lnbico (void) protected
Definition at line 1404 of file wnchyppr.cpp.
References bico, colors, LnFac(), m, and omega.
Referenced by integrate(), and laplace().
void CMultiWalleniusNCHypergeometric::mean (double * mu)
Definition at line 1336 of file wnchyppr.cpp.
References colors, E, FatalError(), LN2, m, MAXCOLORS, n, N, omega, and pow2_1().
Referenced by main(), CMultiWalleniusNCHypergeometricMoments::moments(), and StochasticLib3::MultiWalleniusNCHyp().
void CMultiWalleniusNCHypergeometric::mean (double * mu)
double CMultiWalleniusNCHypergeometric::probability (int32_t * x)
Definition at line 1869 of file wnchyppr.cpp.
References accuracy, binoexpand(), colors, E, FatalError(), findpars(), integrate(), laplace(), m, n, N, omega, CWalleniusNCHypergeometric::probability(), and w.
Referenced by CMultiWalleniusNCHypergeometricMoments::loop(), and StochasticLib3::MultiWalleniusNCHyp().
double CMultiWalleniusNCHypergeometric::probability (int32_t * x)
double CMultiWalleniusNCHypergeometric::search_inflect (double t_from, double t_to) protected
Definition at line 1773 of file wnchyppr.cpp.
References colors, E, FatalError(), LN2, MAXCOLORS, omega, pow2_1(), r, and rd.
Referenced by integrate().
double CMultiWalleniusNCHypergeometric::search_inflect (double t_from, double t_to) protected
void CMultiWalleniusNCHypergeometric::SetParameters (int32_t n, int32_t * m, double * odds, int colors)
void CMultiWalleniusNCHypergeometric::SetParameters (int32_t n, int32_t * m, double * odds, int colors)
Definition at line 1320 of file wnchyppr.cpp.
References colors, FatalError(), m, n, N, omega, and r.
Referenced by CMultiWalleniusNCHypergeometric().
Member Data Documentation
double CMultiWalleniusNCHypergeometric::accuracy protected
Definition at line 513 of file stocc.h.
Referenced by CMultiWalleniusNCHypergeometric(), integrate(), laplace(), CMultiWalleniusNCHypergeometricMoments::loop(), and probability().
double CMultiWalleniusNCHypergeometric::bico protected
Definition at line 523 of file stocc.h.
Referenced by integrate_step(), and lnbico().
int CMultiWalleniusNCHypergeometric::colors protected
Definition at line 518 of file stocc.h.
Referenced by binoexpand(), findpars(), integrate_step(), laplace(), lnbico(), CMultiWalleniusNCHypergeometricMoments::loop(), mean(), CMultiWalleniusNCHypergeometricMoments::moments(), probability(), search_inflect(), and SetParameters().
int CMultiWalleniusNCHypergeometric::Dummy_align protected
Definition at line 519 of file stocc.h.
double CMultiWalleniusNCHypergeometric::E protected
Definition at line 521 of file stocc.h.
Referenced by findpars(), integrate(), mean(), probability(), and search_inflect().
int32_t * CMultiWalleniusNCHypergeometric::m protected
Definition at line 516 of file stocc.h.
Referenced by binoexpand(), findpars(), lnbico(), CMultiWalleniusNCHypergeometricMoments::loop(), mean(), CMultiWalleniusNCHypergeometricMoments::moments(), probability(), and SetParameters().
int32_t CMultiWalleniusNCHypergeometric::n protected
Definition at line 514 of file stocc.h.
Referenced by binoexpand(), CMultiWalleniusNCHypergeometricMoments::loop(), mean(), CMultiWalleniusNCHypergeometricMoments::moments(), probability(), and SetParameters().
int32_t CMultiWalleniusNCHypergeometric::N protected
Definition at line 515 of file stocc.h.
Referenced by mean(), probability(), and SetParameters().
double * CMultiWalleniusNCHypergeometric::omega protected
Definition at line 512 of file stocc.h.
Referenced by binoexpand(), findpars(), integrate_step(), laplace(), lnbico(), mean(), probability(), search_inflect(), and SetParameters().
double CMultiWalleniusNCHypergeometric::phi2d protected
Definition at line 521 of file stocc.h.
Referenced by findpars(), and laplace().
double CMultiWalleniusNCHypergeometric::r protected
Definition at line 521 of file stocc.h.
Referenced by findpars(), integrate_step(), laplace(), search_inflect(), and SetParameters().
double CMultiWalleniusNCHypergeometric::rd protected
Definition at line 521 of file stocc.h.
Referenced by findpars(), integrate(), integrate_step(), laplace(), and search_inflect().
double CMultiWalleniusNCHypergeometric::w protected
Definition at line 521 of file stocc.h.
Referenced by findpars(), integrate(), laplace(), and probability().
double CMultiWalleniusNCHypergeometric::wr protected
Definition at line 521 of file stocc.h.
Referenced by findpars().
int32_t * CMultiWalleniusNCHypergeometric::x protected
Definition at line 517 of file stocc.h.
Referenced by CMultiWalleniusNCHypergeometricMoments::loop().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/wnchyppr.cpp
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/wnchyppr.cpp