SMODT-documentation: StochasticLib3 Class Reference
StochasticLib3 Class Reference
#include <stocc.h>
Public Member Functions
StochasticLib3 (int seed)
void SetAccuracy (double accur)
int32_t WalleniusNCHyp (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHyp (int32_t n, int32_t m, int32_t N, double odds)
void MultiWalleniusNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
void MultiComplWalleniusNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
void MultiFishersNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
StochasticLib3 (int seed)
void SetAccuracy (double accur)
int32_t WalleniusNCHyp (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHyp (int32_t n, int32_t m, int32_t N, double odds)
void MultiWalleniusNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
void MultiComplWalleniusNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
void MultiFishersNCHyp (int32_t *destination, int32_t *source, double *weights, int32_t n, int colors)
Public Member Functions inherited from StochasticLib1
StochasticLib1 (int seed)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
StochasticLib1 (int seed)
int Bernoulli (double p)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
int32_t Poisson (double L)
int32_t Binomial (int32_t n, double p)
int32_t Hypergeometric (int32_t n, int32_t m, int32_t N)
void Multinomial (int32_t *destination, double *source, int32_t n, int colors)
void Multinomial (int32_t *destination, int32_t *source, int32_t n, int colors)
void MultiHypergeometric (int32_t *destination, int32_t *source, int32_t n, int colors)
void Shuffle (int *list, int min, int n)
StochasticLib1 (int seed)
int Bernoulli (double p)
double Normal (double m, double s)
double NormalTrunc (double m, double s, double limit)
int32_t Poisson (double L)
int32_t Binomial (int32_t n, double p)
int32_t Hypergeometric (int32_t n, int32_t m, int32_t N)
void Multinomial (int32_t *destination, double *source, int32_t n, int colors)
void Multinomial (int32_t *destination, int32_t *source, int32_t n, int colors)
void MultiHypergeometric (int32_t *destination, int32_t *source, int32_t n, int colors)
void Shuffle (int *list, int min, int n)
Protected Member Functions
int32_t WalleniusNCHypUrn (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypInversion (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypTable (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHypInversion (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypUrn (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypInversion (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypTable (int32_t n, int32_t m, int32_t N, double odds)
int32_t WalleniusNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHypInversion (int32_t n, int32_t m, int32_t N, double odds)
int32_t FishersNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds)
Protected Member Functions inherited from StochasticLib1
int32_t PoissonInver (double L)
int32_t PoissonRatioUniforms (double L)
int32_t PoissonLow (double L)
int32_t BinomialInver (int32_t n, double p)
int32_t BinomialRatioOfUniforms (int32_t n, double p)
int32_t HypInversionMod (int32_t n, int32_t M, int32_t N)
int32_t HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N)
int32_t PoissonInver (double L)
int32_t PoissonRatioUniforms (double L)
int32_t PoissonLow (double L)
int32_t BinomialInver (int32_t n, double p)
int32_t BinomialRatioOfUniforms (int32_t n, double p)
int32_t HypInversionMod (int32_t n, int32_t M, int32_t N)
int32_t HypRatioOfUnifoms (int32_t n, int32_t M, int32_t N)
Protected Attributes
double accuracy
int32_t fnc_n_last
int32_t fnc_m_last
int32_t fnc_N_last
int32_t fnc_bound
double fnc_o_last
double fnc_f0
double fnc_scale
double fnc_a
double fnc_h
double fnc_lfm
double fnc_logb
int32_t wnc_n_last
int32_t wnc_m_last
int32_t wnc_N_last
double wnc_o_last
int32_t wnc_bound1
int32_t wnc_bound2
int32_t wnc_mode
double wnc_a
double wnc_h
double wnc_k
int UseChopDown
double wall_ytable [WALL_TABLELENGTH]
int32_t wall_tablen
int32_t wall_x1
Protected Attributes inherited from StochasticLib1
double normal_x2
int normal_x2_valid
int32_t hyp_n_last
int32_t hyp_m_last
int32_t hyp_N_last
int32_t hyp_mode
int32_t hyp_mp
int32_t hyp_bound
double hyp_a
double hyp_h
double hyp_fm
double pois_L_last
double pois_f0
double pois_a
double pois_h
double pois_g
int32_t pois_bound
int32_t bino_n_last
double bino_p_last
int32_t bino_mode
int32_t bino_bound
double bino_a
double bino_h
double bino_g
double bino_r1
Additional Inherited Members
Static Protected Member Functions inherited from StochasticLib1
static double fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n)
static double fc_lnpk (int32_t k, int32_t N_Mn, int32_t M, int32_t n)
Detailed Description
Definition at line 392 of file stocc.h.
Constructor & Destructor Documentation
StochasticLib3::StochasticLib3 (int seed)
Definition at line 44 of file stoc3.cpp.
References fnc_m_last, fnc_N_last, fnc_n_last, fnc_o_last, SetAccuracy(), wnc_m_last, wnc_N_last, wnc_n_last, and wnc_o_last.
StochasticLib3::StochasticLib3 (int seed)
Member Function Documentation
int32_t StochasticLib3::FishersNCHyp (int32_t n, int32_t m, int32_t N, double odds)
Definition at line 792 of file stoc3.cpp.
References FatalError(), FishersNCHypInversion(), FishersNCHypRatioOfUnifoms(), StochasticLib1::Hypergeometric(), and n.
Referenced by main(), and MultiFishersNCHyp().
int32_t StochasticLib3::FishersNCHyp (int32_t n, int32_t m, int32_t N, double odds)
int32_t StochasticLib3::FishersNCHypInversion (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 868 of file stoc3.cpp.
References fnc_f0, fnc_m_last, fnc_N_last, fnc_n_last, fnc_o_last, fnc_scale, and n.
Referenced by FishersNCHyp().
int32_t StochasticLib3::FishersNCHypInversion (int32_t n, int32_t m, int32_t N, double odds) protected
int32_t StochasticLib3::FishersNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds) protected
int32_t StochasticLib3::FishersNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 942 of file stoc3.cpp.
References StochasticLib1::fc_lnpk(), fnc_a, fnc_bound, fnc_h, fnc_lfm, fnc_logb, fnc_m_last, fnc_N_last, fnc_n_last, fnc_o_last, and n.
Referenced by FishersNCHyp().
void StochasticLib3::MultiComplWalleniusNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
void StochasticLib3::MultiComplWalleniusNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
Definition at line 760 of file stoc3.cpp.
References colors, FatalError(), MAXCOLORS, and MultiWalleniusNCHyp().
Referenced by main().
void StochasticLib3::MultiFishersNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
void StochasticLib3::MultiFishersNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
Definition at line 1016 of file stoc3.cpp.
References accuracy, colors, FatalError(), FishersNCHyp(), StochasticLib1::Hypergeometric(), MAXCOLORS, n, and CMultiFishersNCHypergeometric::variance().
Referenced by main().
void StochasticLib3::MultiWalleniusNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
void StochasticLib3::MultiWalleniusNCHyp (int32_t * destination, int32_t * source, double * weights, int32_t n, int colors)
Definition at line 377 of file stoc3.cpp.
References accuracy, colors, FatalError(), StochasticLib1::Hypergeometric(), MAXCOLORS, CMultiWalleniusNCHypergeometric::mean(), n, progressbar.example::p, CWalleniusNCHypergeometric::probability(), CMultiWalleniusNCHypergeometric::probability(), and WalleniusNCHyp().
Referenced by main(), and MultiComplWalleniusNCHyp().
void StochasticLib3::SetAccuracy (double accur)
Definition at line 57 of file stoc3.cpp.
References accuracy.
Referenced by StochasticLib3().
void StochasticLib3::SetAccuracy (double accur)
int32_t StochasticLib3::WalleniusNCHyp (int32_t n, int32_t m, int32_t N, double odds)
Definition at line 70 of file stoc3.cpp.
References FatalError(), StochasticLib1::Hypergeometric(), n, WalleniusNCHypRatioOfUnifoms(), WalleniusNCHypTable(), and WalleniusNCHypUrn().
Referenced by main(), and MultiWalleniusNCHyp().
int32_t StochasticLib3::WalleniusNCHyp (int32_t n, int32_t m, int32_t N, double odds)
int32_t StochasticLib3::WalleniusNCHypInversion (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 316 of file stoc3.cpp.
References accuracy, CWalleniusNCHypergeometric::mean(), n, CWalleniusNCHypergeometric::probability(), and wall_x1.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::WalleniusNCHypInversion (int32_t n, int32_t m, int32_t N, double odds) protected
int32_t StochasticLib3::WalleniusNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds) protected
int32_t StochasticLib3::WalleniusNCHypRatioOfUnifoms (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 195 of file stoc3.cpp.
References accuracy, CWalleniusNCHypergeometric::BernouilliH(), CWalleniusNCHypergeometric::mean(), n, CWalleniusNCHypergeometric::probability(), UseChopDown, WalleniusNCHypInversion(), wnc_a, wnc_bound1, wnc_bound2, wnc_h, wnc_k, wnc_m_last, wnc_mode, wnc_N_last, wnc_n_last, and wnc_o_last.
Referenced by WalleniusNCHyp(), and WalleniusNCHypTable().
int32_t StochasticLib3::WalleniusNCHypTable (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 155 of file stoc3.cpp.
References CWalleniusNCHypergeometric::MakeTable(), n, WALL_TABLELENGTH, wall_tablen, wall_x1, wall_ytable, WalleniusNCHypRatioOfUnifoms(), wnc_m_last, wnc_n_last, wnc_N_last, and wnc_o_last.
Referenced by WalleniusNCHyp().
int32_t StochasticLib3::WalleniusNCHypTable (int32_t n, int32_t m, int32_t N, double odds) protected
int32_t StochasticLib3::WalleniusNCHypUrn (int32_t n, int32_t m, int32_t N, double odds) protected
Definition at line 128 of file stoc3.cpp.
Referenced by WalleniusNCHyp().
int32_t StochasticLib3::WalleniusNCHypUrn (int32_t n, int32_t m, int32_t N, double odds) protected
Member Data Documentation
double StochasticLib3::accuracy protected
Definition at line 413 of file stocc.h.
Referenced by MultiFishersNCHyp(), MultiWalleniusNCHyp(), SetAccuracy(), WalleniusNCHypInversion(), and WalleniusNCHypRatioOfUnifoms().
double StochasticLib3::fnc_a protected
Definition at line 420 of file stocc.h.
Referenced by FishersNCHypRatioOfUnifoms().
int32_t StochasticLib3::fnc_bound protected
Definition at line 417 of file stocc.h.
Referenced by FishersNCHypRatioOfUnifoms().
double StochasticLib3::fnc_f0 protected
Definition at line 419 of file stocc.h.
Referenced by FishersNCHypInversion().
double StochasticLib3::fnc_h protected
Definition at line 421 of file stocc.h.
Referenced by FishersNCHypRatioOfUnifoms().
double StochasticLib3::fnc_lfm protected
Definition at line 422 of file stocc.h.
Referenced by FishersNCHypRatioOfUnifoms().
double StochasticLib3::fnc_logb protected
Definition at line 423 of file stocc.h.
Referenced by FishersNCHypRatioOfUnifoms().
int32_t StochasticLib3::fnc_m_last protected
Definition at line 416 of file stocc.h.
Referenced by FishersNCHypInversion(), FishersNCHypRatioOfUnifoms(), and StochasticLib3().
int32_t StochasticLib3::fnc_N_last protected
Definition at line 416 of file stocc.h.
Referenced by FishersNCHypInversion(), FishersNCHypRatioOfUnifoms(), and StochasticLib3().
int32_t StochasticLib3::fnc_n_last protected
Definition at line 416 of file stocc.h.
Referenced by FishersNCHypInversion(), FishersNCHypRatioOfUnifoms(), and StochasticLib3().
double StochasticLib3::fnc_o_last protected
Definition at line 418 of file stocc.h.
Referenced by FishersNCHypInversion(), FishersNCHypRatioOfUnifoms(), and StochasticLib3().
double StochasticLib3::fnc_scale protected
Definition at line 419 of file stocc.h.
Referenced by FishersNCHypInversion().
int StochasticLib3::UseChopDown protected
Definition at line 433 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::wall_tablen protected
Definition at line 436 of file stocc.h.
Referenced by WalleniusNCHypTable().
int32_t StochasticLib3::wall_x1 protected
Definition at line 437 of file stocc.h.
Referenced by WalleniusNCHypInversion(), and WalleniusNCHypTable().
double StochasticLib3::wall_ytable protected
Definition at line 435 of file stocc.h.
Referenced by WalleniusNCHypTable().
double StochasticLib3::wnc_a protected
Definition at line 430 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::wnc_bound1 protected
Definition at line 428 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::wnc_bound2 protected
Definition at line 428 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
double StochasticLib3::wnc_h protected
Definition at line 431 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
double StochasticLib3::wnc_k protected
Definition at line 432 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::wnc_m_last protected
Definition at line 426 of file stocc.h.
Referenced by StochasticLib3(), WalleniusNCHypRatioOfUnifoms(), and WalleniusNCHypTable().
int32_t StochasticLib3::wnc_mode protected
Definition at line 429 of file stocc.h.
Referenced by WalleniusNCHypRatioOfUnifoms().
int32_t StochasticLib3::wnc_N_last protected
Definition at line 426 of file stocc.h.
Referenced by StochasticLib3(), WalleniusNCHypRatioOfUnifoms(), and WalleniusNCHypTable().
int32_t StochasticLib3::wnc_n_last protected
Definition at line 426 of file stocc.h.
Referenced by StochasticLib3(), WalleniusNCHypRatioOfUnifoms(), and WalleniusNCHypTable().
double StochasticLib3::wnc_o_last protected
Definition at line 427 of file stocc.h.
Referenced by StochasticLib3(), WalleniusNCHypRatioOfUnifoms(), and WalleniusNCHypTable().
The documentation for this class was generated from the following files:
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/stocc.h
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/stoc3.cpp
/mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/toolboxes/rnd/stoc3.cpp