SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/ex-evol1.cpp File Reference
ex-evol1.cpp File Reference
#include <time.h>
#include "randomc.h"
#include "mersenne.cpp"
#include "stocc.h"
#include "stoc1.cpp"
#include "stoc3.cpp"
#include "userintf.cpp"
#include "wnchyppr.cpp"
#include "fnchyppr.cpp"
Functions
void SplitIntoGenotypes (int32_t *genotypes, int32_t *genes, StochasticLib1 &stoc)
int main ()
Function Documentation
int main ()
Definition at line 71 of file ex-evol1.cpp.
References StochasticLib1::Binomial(), EndOfProgram(), StochasticLib3::MultiComplWalleniusNCHyp(), StochasticLib1::Multinomial(), StochasticLib1::Normal(), StochasticLib1::Poisson(), and SplitIntoGenotypes().
void SplitIntoGenotypes (int32_t * genotypes, int32_t * genes, StochasticLib1 & stoc)
Definition at line 50 of file ex-evol1.cpp.
References StochasticLib1::Hypergeometric().
Referenced by main().