SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/rnd/erfresmk.cpp File Reference
erfresmk.cpp File Reference
#include <math.h>
#include <stdlib.h>
#include "stocc.h"
Functions
double Erf (double x)
double ErfC (double x)
double InvErfC (double y)
long double ErfResidue (long double x, int l)
int main ()
Variables
static const double rsqrtpi2 = 1.12837916709551257390
static const double rsqrtpi = 0.564189583547756286948
static const double sqrt2 = 1.41421356237309504880
Function Documentation
double Erf (double x)
Definition at line 69 of file erfresmk.cpp.
Referenced by CWalleniusNCHypergeometric::BernouilliH(), Erf(), and ErfC().
double ErfC (double x)
Definition at line 103 of file erfresmk.cpp.
References Erf(), and rsqrtpi.
Referenced by ErfC(), and InvErfC().
long double ErfResidue (long double x, int l)
Definition at line 157 of file erfresmk.cpp.
Referenced by main().
double InvErfC (double y)
Definition at line 140 of file erfresmk.cpp.
References ErfC(), and rsqrtpi2.
Referenced by main().
int main ()
Definition at line 186 of file erfresmk.cpp.
References ERFRES_B, ERFRES_E, ERFRES_L, ERFRES_N, ERFRES_S, ErfResidue(), InvErfC(), and sqrt2.
Variable Documentation
const double rsqrtpi = 0.564189583547756286948 static
Definition at line 63 of file erfresmk.cpp.
Referenced by Erf(), and ErfC().
const double rsqrtpi2 = 1.12837916709551257390 static
Definition at line 62 of file erfresmk.cpp.
Referenced by Erf(), and InvErfC().
const double sqrt2 = 1.41421356237309504880 static
Definition at line 64 of file erfresmk.cpp.
Referenced by main().