SMODT-documentation: /mnt/Data1/Todai_Work/EclipseWorkspace/SMODT/code/cppSide/simAnnealOrbSimulator.cpp File Reference
simAnnealOrbSimulator.cpp File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <sstream>
#include <math.h>
#include <time.h>
#include "toolboxes/orbToolboxes.h"
#include "simAnnealOrbSimFunc.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
This is the "main" that performs the Simulated Annealing process for a single chain of a multi or single chain/thread/process Simulated Annealing simulation started by the Python file BinaryOrbSimStarterDuo.py and controlled with the MCMC_ProcessManagerDuo. It will perform the set up tasks, call the simAnnealOrbSimFunc to perform the Simulated Annealing for the chain based on the input settings. After the chain process is complete it will perform the requested wrap up and statistical calculations requested then write all the output files to disk for the wrap up tasks and plotting done by Python after all the chains are complete. The
Author:
Kyle Mede, kylem.nosp@m.ede@.nosp@m.astro.nosp@m.n.s..nosp@m.u-tok.nosp@m.yo.a.nosp@m.c.jp
Definition at line 15 of file simAnnealOrbSimulator.cpp.
References simAnealOrbFuncObj::a_total_sigma, SimSettingsObj::a_totalMAX, SimSettingsObj::a_totalMIN, outputDataType::a_totals, simAnealOrbFuncObj::argPeri_deg_sigma, SimSettingsObj::argPeri_degMAX, SimSettingsObj::argPeri_degMIN, outputDataType::argPeri_degs, simAnealOrbFuncObj::bestOrbit, simAnealOrbFuncObj::chiSquaredMin, outputDataType::chiSquareds, outputDataType::data_filename, DIdataObj::dataLoadUp(), RVdataObj::dataLoadUp(), SimSettingsObj::DIdataFilename, simAnealOrbFuncObj::DIdo, SimSettingsObj::DIonly, simAnealOrbFuncObj::DIt, generalTools::DItoolsParamLoadUp(), simAnealOrbFuncObj::e_sigma, simAnealOrbFuncObj::earliestEpoch, generalTools::earliestEpochFinder(), SimSettingsObj::eMAX, SimSettingsObj::eMIN, outputDataType::es, generalTools::fileWriter(), simAnealOrbFuncObj::inclination_deg_sigma, SimSettingsObj::inclination_degMAX, SimSettingsObj::inclination_degMIN, outputDataType::inclination_degs, SimSettingsObj::K_MAX, SimSettingsObj::K_MIN, simAnealOrbFuncObj::K_sigma, outputDataType::Ks, generalTools::logFileWriter(), simAnealOrbFuncObj::longAN_deg_sigma, SimSettingsObj::longAN_degMAX, SimSettingsObj::longAN_degMIN, outputDataType::longAN_degs, SimSettingsObj::numSamples, simAnealOrbFuncObj::numSamples_SA, outputDataType::numSamplesAccepted, generalTools::numSamplesStringMaker(), simAnealOrbFuncObj::ODT, simAnealOrbFuncObj::offset_sigmas, simAnealOrbFuncObj::one_over_nu_DI, simAnealOrbFuncObj::one_over_nu_RV, simAnealOrbFuncObj::one_over_nu_TOTAL, simAnealOrbFuncObj::period_sigma, SimSettingsObj::periodMAX, SimSettingsObj::periodMIN, outputDataType::periods, simAnealOrbFuncObj::randSeed, SimSettingsObj::RVdataFilename, simAnealOrbFuncObj::RVdo, SimSettingsObj::RVoffsetMAXs, SimSettingsObj::RVoffsetMINs, outputDataType::RVoffsets, SimSettingsObj::RVonly, simAnealOrbFuncObj::saveEachInt, SimSettingsObj::settings_and_InputDataDir, SimSettingsObj::settingsLoadUp(), simAnealOrbFuncObj::sigmaPercent, SimSettingsObj::silent, simAnealOrbFuncObj::simulator(), simAnealOrbFuncObj::sqrtECosomega_sigma, simAnealOrbFuncObj::sqrtESinomega_sigma, simAnealOrbFuncObj::SSlogStr, simAnealOrbFuncObj::SSO, SimSettingsObj::startTemp, simAnealOrbFuncObj::startTemp, simAnealOrbFuncObj::SYSdo, SimSettingsObj::SystemDataFilename, DataObj::systemDataLoadUp(), SimSettingsObj::T_Max, SimSettingsObj::T_Min, simAnealOrbFuncObj::T_sigma, outputDataType::Tcs, simAnealOrbFuncObj::tempStepSizePercent, outputDataType::Ts, SimSettingsObj::verbose, and DItools::verbose.